### ISSUE TITLE
ng-repeat with an active class when ng-click does not work

### ISSUE THREAD

**Issue by jsantana90** [Urigo/angular-meteor#1040]
I'm trying to do a normal angular ng-repeat which has an list of buttons which an user can click.

Each button individually will have a class active when clicked and the others will have the active class removed. In angular alone it works normally, but using angular-meteor seems to not be working.

Here's my code:
```html
<ul class="nav nav-pills center-pills" ng-init="activeIndex = 0">
  <li ng-repeat="kit in kits" ng-class="{active:(activeIndex==$index)}"><a ng-click="activeIndex = $index" href="">{{kit.name}}</a></li>
</ul>
```

When I click on one of them, it gets the active class but doesn't remove the active class from the other buttons.

Do I have the code right? or is it an angular-meteor issue?

**Comment by ThomsC** [comment]
- I don't see how activeIndex should increase as the ng-repeat goes on.

- In ng-class it should be string `ng-class="{'active': ...}"`
     Here is a great tutorial on how to use it : https://scotch.io/tutorials/the-many-ways-to-use-ngclass

- You should create a method in ng-click and not do your logic inside the view

**Comment by ozsay** [comment]
This issue is related to `angular` not `angular-meteor`, and it's not really an issue but this is how angular is implemented.

From my understanding, you wanted one place to store `activeIndex` but it doesn't happen this way.

when you use ng-repeat, it will create a scope for each of the DOM elements. If you have 3 elements in the `kits` array then angular will create 3 scopes that will look something like this:

```
scope1: {
  kit: {name: 'a'},
  activeIndex: 0
}

scope2: {
  kit: {name: 'b'},
  activeIndex: 0
}

scope3: {
  kit: {name: 'c'},
  activeIndex: 0
}
```

you told angular to set `activeIndex` on click.

What really happens is, it will change the local property for the corresponding scope.

If you click on the second element this is the scopes map:

```
scope1: {
  kit: {name: 'a'},
  activeIndex: 0
}

scope2: {
  kit: {name: 'b'},
  activeIndex: 1
}

scope3: {
  kit: {name: 'c'},
  activeIndex: 0
}
```

Then you click on the last one:

scope1: {
  kit: {name: 'a'},
  activeIndex: 0
}

scope2: {
  kit: {name: 'b'},
  activeIndex: 1
}

scope3: {
  kit: {name: 'c'},
  activeIndex: 2
}
```

so, for each of the scopes that you press, the `ngClass` condition is valid and that's why this will not work.

A way to solve it to change `activeIndex` to an object. This way, angular will keep a reference to the object for each of the scopes and not copy it's value:

```html
<ul class="nav nav-pills center-pills" ng-init="activeIndex = {index: 0}">
  <li ng-repeat="kit in kits" ng-class="{active:(activeIndex.index ==$index)}"><a ng-click="activeIndex.index = $index" href="">{{kit.name}}</a></li>
</ul>
```

now when you click the second element it will be changed in all the scopes:

scope1: {
  kit: {name: 'a'},
  activeIndex: {index: 1}
}

scope2: {
  kit: {name: 'b'},
  activeIndex: {index: 1}
}

scope3: {
  kit: {name: 'c'},
  activeIndex: {index: 1}
}
```

check out the official explanation https://github.com/angular/angular.js/wiki/Understanding-Scopes

**Comment by jsantana90** [comment]
@ozsay thank you, I'll definitely read more about it, thank you so much for taking the time to explain it.

**Comment by Dominic-Damoah** [comment]
Very useful explanation. thanks so much. saved me a lot of time

**Comment by sasikala-R** [comment]
Thank You so much for sharing the explanation here.
