### ISSUE TITLE
Angular2 Tutorial: Clarify Attribute / Property binding

### ISSUE THREAD

**Issue by ShMcK** [Urigo/angular-meteor#1101]
In step 15 and and several other places of the Angular 2 tutorial, I believe there is _some confusion over_ **attribute & property binding**. I may be wrong, but my understanding is:

- attribute binding (`<my-component foo="stringValueOnly">`)

Using regular attributes in HTML
> ...  an attribute is always a string

- property binding (`<my-component [foo]="anyValue">`)

Binding any value to an HTML property
> Property binding is the syntax where we use brackets to bind values to an element’s property. 

Quotes from [this article on template syntax](http://blog.thoughtram.io/angular/2015/08/11/angular-2-template-syntax-demystified-part-1.html) vetted by the Angular team. 

Please check, if the terminology is off, we can just quickly reword a few parts of the tutorial.

**Comment by barbatus** [comment]
Here http://www.w3schools.com/tags/att_global_hidden.asp it says otherwise.
As I understand there is no any agreement on this yet. I'd seen those articles you pointed before started writing that step. Angular 2 team might prefer one terminology, but `attribute`, as I believe, is what most of developers are used to think of about this construction, that's why I chose it. I don't no.

**Comment by Urigo** [comment]
updated in the version of the tutorial
