### ISSUE TITLE
The Future of Meteor, and what to do about it.

### ISSUE THREAD

**Issue by MilosStanic** [Urigo/angular-meteor#1120]
Hi @Urigo, @barbatus  et al., 

Since we don't have a forum or some better way to exchange ideas, I thought this would be an appropriate place to do it. If you think otherwise, please direct me to where I should repost this for discussion. 

I read today a pretty disturbing article that regards the future of our sub-community of Meteor. 
Sacha Greif wrote a highly opinionated article about Meteor's future [here](https://www.discovermeteor.com/blog/the-state-of-meteor-part-2-what-happens-next/).
It is his opinion that React will prevail as the choice for front-end in Meteor, but the reasons he give in favor of his opinion can all be applied to justify an opposite opinion that Angular will prevail. 

Him being a very influential individual in the Meteor community, and considering the fact that most people coming from Blaze will not know the pros and cons of React vs. Angular, he may considerably use his influence the broad community to, indeed, skew the community to opt for React against Angular.

One strong point, that is easily missed in his article is the existence of the [Mantra](https://kadirahq.github.io/mantra/) project that is run by Kadira of Arunoda Susiripala, who is also a person of immense influence in the broad Meteor community. In this Mantra project he is also advocating a switch to React, and basing his project on it. This is especially threatening for the future of Angular in Meteor world, because, as you already know, Kadira and Arunoda are the ones who developed the Meteor Up deployment system which is the defacto standard in the broader Meteor community for deploying applications.

Therefore it is my opinion and hope, that we in the angular-meteor community must stand and put an extra effort into promoting Angular as a viable UI option for Meteor, in order to win community support for developing other packages needed to support our small eco-system. 

Mantra project itself is a good source to brainpick ideas for our project here.

Thank you all for your attention, and I hope it was not a waste of time.

**Comment by Tallyb** [comment]
@MilosStanic  I think it is a good discussion for the forums.meteor.com. We should also increase our presence there.

**Comment by MilosStanic** [comment]
I see there's already a topic about Sacha's article with a flamewar going on over there at https://forums.meteor.com/t/the-state-of-meteor-part-2-what-happens-next/16766

But I thought we need a place to make a strategy to counter the React initiative. It's not that I have anything personal against React, but they may steal the community away from us.

**Comment by barbatus** [comment]
@MilosStanic I’ve heard that MDG ditched ideas of Blaze2 based on React in favor of supporting Blaze, React, and Angular2 all together. I believe MDG still decides where to go not just famous people in the community even if they are Sacha or Arunoda.

**Comment by MilosStanic** [comment]
Maybe angular-meteor site needs a forum, and/or blog. Forum would be needed for discussions like this, and blog would be nice for publishing articles about best practices and real-world use-cases. 
Also, it would be nice of @Urigo and @barbatus to keep us a little more informed about the plans for the future of angular2-meteor. 
I believe most of us are working on real-life angular-meteor applications, and we need a bit more encouragement and reassuring about the future to stay with Meteor, instead of investigating other options for backend to Angular(2).

**Comment by kamilkisiela** [comment]
```
Maybe angular-meteor site needs a forum, and/or blog.
```
@MilosStanic I think [angular category](https://forums.meteor.com/c/angular) at meteor's forum is enough.

About blog, that is a good idea. Something like `guide.meteor.com` would be great. Especially with support from angular-meteor's community.

**Comment by jacobdr** [comment]
Happy to see this conversation going on. 




I think we should separate the topic of angular advocacy in the meteor community from an internal discussion of ways to improve our own angular-meteor community -- be that through new features on the website, meet ups, voting, etc. Strong work on the latter empowers the former. 




So on that topic I would like to propose: 




- Creation of email list for "users" and "dev" so that GitHub is used for issues/bugs, user list for questions like "how do I do this" or "check out this cool shit I made", and dev list for coordinating RCs, questions of API development, etc




- Starting to release RCs or maintain strong development branch / nightlies so that we don't run into quick patch problems 




- Creating a "receipe" section on the website that will provide starter code/ snippets for common design patterns (example: the discussion of reactive factories/services going on on be other thread) that are super helpful, but that don't belong in the API documentation. 




- Finally, I hate to see all these email threads about broken tutorial examples. With the lightening speed at which node, meteor, and angular change I know that it is hard to keep documentation up to date. But I think we can find a solution in enforcing stricter test standards. I.e. Every tutorial example needs a test case and website documentation PR requires passing CI tests. 




My two cents/ 3 shekels/ 7 angular dollars. 




JR 



—

**Comment by plantsmiles** [comment]
Agreed, a place for us _cool_ people would be great.  I've tried a combination of posting stuff between stack overflow and the meteor forums in regards to angular help but it feels like they just get buried and forgotten.

Even though MDG has stated they want angular to be a big part of this community, it doesn't really feel like it sometimes.  Which is sort of scary for us using this for production apps.

**Comment by stubailo** [comment]
> Since we don't have a forum or some better way to exchange ideas, I thought this would be an appropriate place to do it. If you think otherwise, please direct me to where I should repost this for discussion.

Personally, I think the Meteor forum would be an awesome place to have this discussion - I don't think the Angular-Meteor community is heard enough by the other people in the general Meteor community, so the place seems a bit skewed.

**Comment by TWKDreamState** [comment]
I do not know if this is relevant, but I'd thought I'd add it. I'm currently a leaner in all things Angular and Meteor.

I work in education and logged in to my schools Microsoft Education Office 365 account where I was greeted with a notice that I could test their new Admin Console. Interestingly, it all seems they have moved to Angular. It's a beta so I guess this might change....

But, it got me thinking, that if MS are investing Angular in one of their MAJOR products, then perhaps the Meteor community should take note and not jump on the wagon of supporting one front-end system. Working with Meteor and Angular has been one of the most interesting projects I've work on and, as with many annoying problems I've encountered (which are usually my incompetence), there have been many 'wow' moments.

I hope the community is not swayed, because (although I am very happy to admit I have no experience in React), it seems that the front-end should not be decided by individuals, but by the programmers.

**Comment by Splaktar** [comment]
Thanks for the link to the [Angular-Meteor forums](https://forums.meteor.com/c/angular)! I wish that it was more prominently featured as a primary link on the angular-material.com site and in Uri's ngConf/AngularConnect/etc presentations.

**Comment by j127** [comment]
React has a problem because of its PATENTS file in Facebook's repos. If you use React/Immutable/etc. It appears to give Facebook the right to infringe on your company's patents while not giving you the same position in return. Software patents suck, but this creates a power imbalance. I think that it would be a bad decision to put React into Meteor, because it would cause some companies to avoid Meteor.

**Comment by stubailo** [comment]
> I think that it would be a bad decision to put React into Meteor, because it would cause some companies to avoid Meteor.

We aren't putting React into Meteor.

**Comment by j127** [comment]
> We aren't putting React into Meteor.

Great :)

**Comment by ThomsC** [comment]
+1

**Comment by Urigo** [comment]
@MilosStanic It is great that you opened this issue and I’m very happy for it.

I haven’t responded so far because I wanted all the Meteor 1.3 things to be done...

First - It’s important to emphasize that the people talking about React are simply community members excited about it, not an official statement from MDG, and everyone has the right to pick their favorite framework.

It looks like our Angular-Meteor community has kept to itself rather than being part of the general Meteor community, so most people in the Meteor community aren't aware of the benefits of Angular at the moment. 

This is why I’ve removed the special forum for Angular Meteor and I’m not fond of our angular-meteor Gitter.
All of those conversations need to take place inside the Meteor and Angular forums and our community’s opinions should be heard much more there.
Also, we need to talk not only on the Angular specific category, but to make our voice heard on the general topics as well.

I think your comment opens a door for the Angular community to take a more active role inside the Meteor community and a start for the Meteor community to take a more active role inside the Angular community.

While I’m here and we are addressing our Angular-Meteor community, I’m going to take the opportunity to expand more about my current personal view and vision. 

So I’m going to address your comments and break it down to a few topics:

* **Angular-Meteor 2 IS the stack**
* **Building a Community inside the larger Javascript Community**
* **The Future of Meteor (and Angular)**

## Angular-Meteor 2 IS my choice of stack
Meteor 1.3 with Angular 2.0 Beta is finally the stack that I’ve been waiting and working for, for years.
Angular 2.0 Beta is finally solid and Meteor 1.3 gives Angular developers the possibility to work directly with npm and the whole Javascript community.

As I see it today, Angular 2.0 is currently my choice for front-end solution and I’ve just given a small lecture about how with all the great benefits and progress React has given us (taking the points from the great Pete Hunt talk - “rethinking best practices”), Angular 2.0 takes those abilities to the next level in every field.
Maybe I should give that talk to a wider audience, maybe in the next ng-conf/react-conf or something… (@aaronfrost)
Also the progress that the Angular team is doing on so many fronts since the Beta was out is extraordinary - You should follow the [Angular Weekly meetings](https://docs.google.com/document/d/150lerb1LmNLuau_a_EznPV1I1UHMTbEl61t4hZ7ZpS0/edit#heading=h.wyupmi438jru) and [Brad Green’s twitter](https://twitter.com/bradlygreen) account and look at what they are doing with Mobile, animations, Web Workers etc...

So I’m not worried that the Meteor community will be focused on React.  the community is smart enough to go with the best existing solutions and now that Angular 2.0 and Meteor 1.3 are available, we have a very good competition that will push everyone forward.
Remember that before Angular Meteor, there was no real solution for UI in Meteor other than Blaze.  We’ve come a long way and we are in a better place than ever.
And look, we even [have stickers](https://www.stickermule.com/marketplace/9686-angular-meteor-sticker)!!!

I’m also learning a lot from the React Meteor integration. It helps me a lot and we share a lot of knowledge to move us all forward.

## Building a Community inside the larger Javascript Community
So now that we have the one great stack to be aligned on, we can think about how to improve it.

We can push forward ideas from Angular like Typescript and dependency injection so that the whole Meteor and Javascript community will benefit.
[Here is a list](https://trello.com/b/tdzPiV3O/angular-meteor-collaboration) I’ve made few months ago for things that I think Meteor and Angular should collaborate on. Both communities should push for those ideas and make the core team members consider them.  PRs and actual code always makes a larger impact...

It’s a combined effort for all of us.
For example - It is strange for me that the Angular Meteor Socially tutorial is one of the most comprehensive full stack Angular 2.0 tutorials out there and in my mind not enough Angular 2.0 developers have tried it yet…
We continue working on the tutorial to create an essential place to learn Web development with
Angular2/Meteor. Our ultimate goal is to make it so clear and neat to become one of the favorite places on Internet to learn Web development from scratch.

Another place we could do more is helping the largest Meteor open source apps like RocketChat and Wekan.io become more aligned with the stack we believe in.

But please don’t assume any of these things will be done without your direct help and work. 
Any help would be appreciated.  
if you want to help but don’t know how - feel free to contact me directly.

The Angular Meteor work is not done by me alone. I’m getting huge amount of great, real-work help from people from the community like @barbatus , @dotansimha , @kamilkisiela , @DAB0mB and many more..  (Hell, we even got PRs from @IgorMinar !!!) and I keep mentioning all of them with every release I make (learned that from the Angular team).

They all contacted me directly through email and we are talking almost daily to plan our work. 
Remember - my personal email is public on my Github profile and if you need to contact me in regards of thoughts, suggestions or anything else, please do not hesitate.
Also, I’ve updated our roadmap into Github milestones ([Angular1.x](https://github.com/urigo/angular-meteor/milestones), [Angular 2.0](https://github.com/urigo/angular2-meteor/milestones)) so you can follow and help more easily.

As developers who know both technologies, we could have a huge part in bringing the two communities together to create a shared conversation that pushes the whole Javascript community forward.

## The future of Meteor (and Angular)

On both sides, Angular and Meteor, we should do more so that the stack will move forward - 

On the Angular front, I think the Angular community and team should be focused almost entirely on mobile.
The team is doing great things with Web Workers and Animations and we should help there. The community should create Components that are targeted to mobile.  
Ionic 2.0 is amazing, it alone is not enough.  NativeScript is not enough. The current Angular 2.0 and React Native integration are not enough. 
We should create real app scenarios and benchmarks to test and show the current state of the art, like creating a Google Inbox clone in Angular 2.0.  fancy numbers are not convincing enough.

We are also working to get more involvement from the core Angular team promoting Angular 2.0 in Meteor meetups, forums and blogs.
We should do the same with the core Ionic team promoting Ionic 2.0 (@adamdbradley , @mlynch , @bensperry).

On the Meteor front, in the last months we see huge progress to address the largest things we care about - mainly embrace npm and a new data integration.

Meteor 1.3 is a huge step for being more aligned with the rest of the Javascript community and npm. @benjamn is leading a phenomenal work that I think the whole Javascript community should be aware of.

On the data front, Meteor is again leading the way with creating a [Reactive GraphQL app data solution](http://info.meteor.com/blog/reactive-graphql) (must read).
This is an amazing work which takes into considerations all the things we learned from Meteor over the years and embraces ideas from Facebook like Flux, Relay, Redux and GraphQL to create the future of app data management.
And Meteor is doing it in a way which is both Front End agnostic so that we could use it with Angular 2.0 or React and DB agnostic so you could use it with SQL, MongoDB or REST.

This work is maybe the most exciting work that is happening in all the Javascript community, and it is being done in collaboration with the relevant teams at Facebook.

## Forks
People are talking a lot about the forks of Meteor.  I think that’s the best thing that could happen to Meteor!!
That means that the Meteor community has matured enough to have highly professional members that can implement their great ideas in the open.
Meteor can learn from those ideas and decide what things it should or shouldn’t use in future versions.
It also gives the community more choices and confidence around the overall solution.

**This is the best time for being an Angular Meteor developer**. Let’s make it even better together.

**Now is the time for Angular Meteor.**

P.S.
This comment is meaningless if it won’t be shared around the Angular, React and Meteor communities…..
Let’s put our energies where we can influence the most.

**Comment by MilosStanic** [comment]
Thank you @Urigo for the most extensive and encouraging answer. 

My original post was written well before Meteor 1.3 was out, and at that time, as the Meteor community influencers started leaning towards React, more and more packages were converted to Atmosphere to help use React with Meteor, and very few Angular packages were converted to Atmosphere. 

Fortunately, Meteor 1.3 took care of that when it included npm, so now any Angular package can be used with Meteor. Although the npm utilization is not yet complete because css assets are not automatically imported to Meteor from npm packages. 

Now, the Angular-Meteor community is pretty much self-dependent. Meteor provides us with the fantastic backend and we can let our imagination fly using all the benefits from the vast npm world.

Regarding the Meteor Forum, it is a self-doomed project because of the nature of Meteor itself. It doesn't do server side rendering, so topics on Meteor Forum are not visible to Google crawlers, so no results come up in search. I've solved 99% of my Meteor problems from Stackoverflow, but not from Meteor Forums. I simply don't have the habit of visiting it. I came from Angular world to Meteor world, so never had the habit. Finally, this is probably one of the most important thing missing to totally round up the Angular-Meteor story --- the server-side rendering. 

Thanks again! I will probably write more, once I chew up again on what you wrote. :)

**Comment by Hongbo-Miao** [comment]
@MilosStanic keep going with Angular 2. I walk between both Angular2-Meteor and Meteor-React. So I know why people recommend React.

I agree that React is using JavaScript to generate HTML is indeed flexible and I love this too. But this has price. My feeling, it starts to become hard to maintain if you have a over 10k lines of code project.
Then Redux this data pattern comes out to solve that. But you can use Redux with Angular 2 [ngrx](https://github.com/ngrx), which work great.

There is a team in Google creating Angular 2, they carefully selected router, form validation, everything and put them together. In the mean time, React only some main people are maintaining.

For meteor-react, let's use router for example, before they use flow-router, now they think to turn to react-router, but yesterday I saw this [React Router is dead. Long live rrtr](https://medium.com/@taion/react-router-is-dead-long-live-rrtr-d229ca30e318). They are all community individual support, not like Google a strong team support.

The feeling using React is more like Individualistic Heroism, you choose every thing by yourself. You have power. It shows freedom. But it takes too much time to make every parts work together well. And those main people in react community are also like Individualistic Heroism: those main individuals are maintaining different individual part of React ecosystem. Meteor-React is same, and Arunoda is a main person (Think about what if one day Arunoda left Meteor-React?). So you cannot always rely on one person. You need rely on a team.

Angular 2 is from a GROUP of Google genius, and also some same other BIG groups like [Valor Software](https://github.com/valor-software) responsible for different parts.

One advantage of React ecosystem is free to choose different part, but this has price too. Everyone uses different parts, which makes the community grow slow, because hard to share experience, hard to choose some core module to improve. So they try to make a standard [Mantra](https://github.com/kadirahq/mantra). Then what is the difference with Angular 2? Besides every parts in Angular 2 are carefully chosen by Google strong team. Angular2-Meteor is also similar. It has a reliable team @Urigo @barbatus @dotansimha @DAB0mB. (Seriously, guys, where are you from? Why all of you can speak Hebrew?)

Right now, the only thing for angular2-meteor I want it to be improved is fast rendering.

I can feel Angular 2 is a really carefully designed project, it already learns almost all good parts from React ecosystem.
Typescript for me seems a clear way, type definitely helps a lot for maintaining when the project is BIG.
RxJS is also a good selling point.

Before I always think why Angular team keeps updating Angular 1 like React. Now I think it is the right decision to create Angular 2 as a brand new instead of keeping improve Angular 1. It is hard to provide a revolution project if just keep updating Angular 1.

@dotansimha I saw you answer the question why choose Angular 2 over React in this [video](https://youtu.be/CKSgBfDssMk?t=18m24s), I would love to give a more clear answer next time, because I have used both Meteor-React and Angular2-Meteor. :)

So my preference now is angular2-meteor > meteor-react > angular1-meteor.

**Comment by mlynch** [comment]
@Urigo happy to help how we can. Don't really agree that what the ecosystem offers isn't enough, plenty of people being successful with all those tools (including Ionic 2). Of course, tons of room to improve.

**Comment by Urigo** [comment]
@MilosStanic why do you think Meteor forums are not crawlable? we use Discourse and it is crawlable..

But I think Stack Overflow is always better for questions, Github Issues are for bugs and feature requests and Meteor Forums for discussion like the one we are having here.

About SSR and fast rendering, it is closer than ever, probably a first working version next week..

@Hongbo-Miao I agree that we can answer the React-Angular question in a better way, maybe you should go to a Meetup and give a lecture on that!

@mlynch I agree, I'm using Ionic and Ionic 2.0 in so many projects and loving every second of it.  it really, without a doubt, made me personally more successful.
I think that showcase apps - maybe an Inbox clone, Facebook's Paper clone,  would make things easier, both for the developers and for convincing large companies to move from full native apps
Facebook made a great move with the F8 app

**Comment by Hongbo-Miao** [comment]
@Urigo yeah, that will be great, I can show some cool stuff especially when using Angular 2 with Meteor.

**Comment by MilosStanic** [comment]
@Urigo I thought Meteor forums were not crawlable simply because when I search Google for Meteor stuff, they never appear in results. That, and knowing the issues with crawlability of Meteor apps, was the reason I made that conclusion. 
Great news about SSR and fast rendering. Can't wait for it!

**Comment by j127** [comment]
Discourse forums are indexable, but maybe don't rank as well as they could. All the content is between noscript tags, which is not ideal for SEO. This is a problem with a lot of newer forum software. (Discourse, NodeBB, Flarum, etc.)

**Comment by mlynch** [comment]
@Urigo glad to hear that 😄 👯. And yes, we need to put out more awesome demos, it's a priority for me this year. We started with a conference app demo a few months back (I suppose F8 has validated/overshadowed that now :P) https://github.com/driftyco/ionic-conference-app

Also, we run a popular discourse forum and so far SEO has been solid.

**Comment by j127** [comment]
> Also, we run a popular discourse forum and so far SEO has been solid.

You can get indexed and even rank with Discourse, but it's unlikely that it will do as well as a site that renders full HTML. Links within `<noscript>` appear to not pass "link juice" well. SPAs can also be _indexed_ (even without the `_escaped_fragment_` parameter now), but I don't think that they tend to rank well either.

(The distinction is _indexing_ vs. _ranking_ -- a site can be indexed perfectly while still not ranking as well as it could.)

**Comment by Urigo** [comment]
@mlynch I wasn't aware if that app, looks really really nice!

**Comment by mlynch** [comment]
@j127 in theory I agree, but in practice we've been nothing but very happy with ranking and Ionic forum posts. I can see it being suboptimal but also "good enough" and a large amount of our traffic comes from search (and a lot of it)

**Comment by Urigo** [comment]
In other news - my post on the official Angular blog is up - https://twitter.com/angularjs/status/723019578264014848
Would love some social sharing love ;)

**Comment by Urigo** [comment]
thanks everyone for the great discussion.
closing, but we can keep on talking ;)

**Comment by MilosStanic** [comment]
Hi all, @Urigo, 

@Hongbo-Miao has pointed out a poll running on Meteor forums [here](https://forums.meteor.com/t/who-uses-what-blaze-angular-react-poll/23130) that reinforces the fears that I expressed in the original post about Meteor community leaning strongly towards React.
The results of the poll reflect the fact that overwhelming majority of people uses React in such a proportion that is not present in the general population of JS programmers outside Meteor stack. What's more, it appears the same proportion of people are using Vue as Angular. Which is certainly not natural distribution outside Meteor world.

So, please give a vote at the above link. Let's make numbers better! :)

Offtopic: looking at another topic at Meteor forum, which is linked to the poll topic above, I stumbled upon @stubailo 's reference on Angular-meteor tutorial "unfortunate" use of allow/deny pattern to restrict access to database. I've never heard of this before, so I'm asking you to fix this in the tutorial. Have a look [here](https://forums.meteor.com/t/proof-that-no-one-uses-allow-deny/23059/9?u=stanke). Uri, I hope Sashko has pointed out this to you. 

Btw, I hope SSR and stuff Uri announced earlier lands soon to angular2-meteor. 

Cheers.

**Comment by stubailo** [comment]
> The results of the poll reflect the fact that overwhelming majority of people uses React in such a proportion that is not present in the general population of JS programmers outside Meteor stack.

I think this actually reinforces @Urigo's desire to merge the community back into the general Meteor one. If Angular-Meteor stays separated from the regular Meteor forums, etc. then their views won't be represented in that venue. So I encourage more people to post about Angular on the Meteor forum, let your opinions be heard!

> I stumbled upon @stubailo 's reference on Angular-meteor tutorial "unfortunate" use of allow/deny pattern to restrict access to database.

I don't think this is a big deal, it could be a fine way to start learning Meteor, and many people use this approach in production. It's just not the approach recommended in the Meteor Guide.

**Comment by Hongbo-Miao** [comment]
@MilosStanic you know I came from React. The more I learn about Angular 2, the more I love it.

**I have a Suggestions for React people at the end. It is fun~**

(At that age, Angular 1 is amazing. After React comes out, compared with React, Angular 1 is bad. Now Angular 2 actually I feel they totally changed a name, because it is too amazing!)

React for me is just one small library, which can be easily used in Angular 2 as a component when you needs.
Angular 2 is sooooo powerful (**RxJS** powered) and it is a future product (**TypeScript** include **ES7** features like Decorators and has its own Type) which saves me a lot of time to write codes.

When I went back to ES6, I feel my codes so ugly. (If you are using ES6 now, the feeling is like going back to ES5).

### 1. TypeScript (ES7 + Type)
#### 1) ES7
**Decorators** are in ES7, you like it, right? And more ES7 feature
#### 2) Type
Type from Typescript is amazing too! I am using **[WebRTC](https://webrtc.org/)** in my project. I have an example of myself. Before I have some codes like this:
```
const configuration = {
  'iceServers': [{ 'url': 'stun:stun.1.google.com:19302' }]
};
```
I have an error actually, but I didn't notice that, after I adding typings file, adding "RTCConfiguration" here, I found the error: I should use "urls" like below instead of "url". It saves me a lot of time to find the error.
```
const configuration: RTCConfiguration = {
  'iceServers': [{ 'urls': 'stun:stun.1.google.com:19302' }]
};
```
### 2. Shadow DOM
I really like Angular 2 is **Shadow DOM**.
#### 1) Handle CSS-style collisions
In each of your component, you can use same name for you CSS, right? And they won't affect each other.
When a lot of people work together, they write their own components, and the codes they write won't affect each other.

#### 2) Handle JavaScript collisions
I am using **[D3.js](https://d3js.org/)**, for example, I have a
```
<svg class="line-chart"></svg>
```
in one of my component.
D3.js is kind of like jQuery. Usually when I select, I do
```
const chart = d3.select('.line-chart')
```
Since React does not support Shadow DOM, I cannot easily reuse. If I want to use twice, I need do `<svg class="line-chart1"></svg>` and `<svg class="line-chart2"></svg>`. Imagine I need 10, or even 100 similar charts...

In Angular 2, things become amazing!
When I reuse this component, I just need do
```
const chart = d3.select(this._element.nativeElement).select('.line-chart')
```
When I reuse this component, they won't affect each other.

### 3. RxJS 5
I don't want to say more, this is just tooooooooooooooooooo powerful.
![image](https://cloud.githubusercontent.com/assets/3375461/15311403/7059b1fe-1bc8-11e6-93ee-b9c274266da3.png)
[When most React people are still excite](https://forums.meteor.com/t/start-using-async-await-instead-of-promises-and-callbacks/17037/30) about **Promise**, we already start to use **RxJS 5** (which is called **Promise++**), and we are using RxJS 5 (not 4).

### 4. Some of my old talk
Also, I wrote [here](https://forums.meteor.com/t/angular-vs-react-todo-tutorials-angular-loc/22970/20?u=hongbo_miao) before, just copied some parts below:

Most people saying they like React more, actually they never tried Angular 2. So don't listen to them.

**It is like a threshold, React's is low while Angular 2's is high.** React is so easy to start, so most people just start to use it. For Angular 2, you need learn more to start to use it.

If you are a designer or just want to build a small project. React is quick to start.
If you plan to build a large project in the beginning, I would recommend Angular 2.

Read [this article](http://blog.mgechev.com/2016/04/10/scalable-javascript-single-page-app-angular2-application-architecture/) to see why Minko Gechev's team goes with Angular 2 instead of React for their new product.

Alibaba, who owns Taobao.com, used React for their website. But now their new product websites also start to use Angular 2.

**Avoid living in a certain technology ecosystem. Always be open to new technologies, otherwise you will fall behind without knowing that. New technologies coming out always have reasons.**


### 5. Suggestions for React people
Please, spend some time and go out of React ecosystem and see the new world. You already fall behind and you just didn't realize. We have a word 井底之蛙(The frog of the well). The story is below:

**The frog lived down in a well where there was all he had to live. One day, a softshelled turtle came by and told him about the sea. 'The sea? Hah! It's paradise in here. Nothing can be better than this well. Why don't you come down and share my joy?'**

**Comment by Urigo** [comment]
@MilosStanic I'm sorry but I hate polls and I hope to never base my decisions on those :)

I have a [vision](https://github.com/Urigo/angular-meteor/issues/1120#issuecomment-209125382) that I believe in and if someone sees that now that great.  if not, that's fine as well, most likely they will see it in a few months ;)

As for popularity, I can't assure you we are better than ever, here is a screenshot of the Google Analytics of the Angular-meteor.com website:
<img width="956" alt="screen shot 2016-05-17 at 8 52 00 pm" src="https://cloud.githubusercontent.com/assets/1297448/15359366/a397af04-1d11-11e6-8a9a-57b9f98d1427.png">

As you can see, the trend if moving for our advantage, in my mind mostly because the Frameworks (Meteor and Angular) are pushing and doing things in the right direction.

@ThomsCass I feel your pain.  I know the first versions of angular-meteor 1.3 created a mess, and you can see that it even reflects on the Analytics.
I take full responsibility on that and now we are at a much better place, you can feel safe using angular-meteor 1.3.10 with the new or the old syntax and everything will be fine.
But I also think that if you want to use React that's fine and good for you, it's most important that you will be successful and earn money doing the things you want.
I will always welcome you back to the community and would love to help in a any way making you successful, whether in Angular or React.

@Hongbo-Miao I love your post, it makes a lot of sense.
About the Allow/Deny thing, my goal and my vision is to have a platform that let you build a first app or first MVP and in the fastest way possible, whether you are experienced developer or not, and then when you want to scale, code size or traffic you know exactly what to do.
That's why I think Allow/Deny is a good thing and not unfortunate.
When your app will get to a place where this is an obstacle, you know exactly what to do with the help of the great Meteor guide (and future chapters of Socially) and it means the MVP version of your app got you in a good place.

I hope my opinion makes sense...

**Comment by MilosStanic** [comment]
@Urigo you're a true inspiration for the community. Thank you for all your work. 
The only thing I wish was better is having some sort of clear roadmap. Knowing which features are planned, for example testing framework, SSR, angular-universal, progressive web apps, etc. And a loose timeframe for those. Particularly for Angular2-Meteor. 

None of us, obviously plans giving up angular2-meteor, because of all the clear benefits it has over other fullstack solutions.

Keep up the good work, and thanks again.

**Comment by Urigo** [comment]
@MilosStanic about a Roadmap, I don't want to duplicate something from Github Issues so I think we would go back to Waffle.io here - https://waffle.io/Urigo/angular-meteor

I will prioritize it and tag issues this week to make it a bit more clear and would love your help in that.

Timelines are hard to estimate but I'll try better at predicting them...

If there are things there that are not specified you can open an issue for those and they will be added there automatically

**Comment by vimes1984** [comment]
@MilosStanic @Urigo god I was away on a project for 3 months and I'm back in the meteor landscape and damn stuff is happening. 
Polls don't mean anything most people don't participate if they even here about it I run 3 meteor apps in production and a few more in the pipe line using angular2/meteor/angular1 and it's taken nearly 20 days to find that poll, it's not representative of the overall community. Some people just quietly sit by the side lines without ever voicing an opinion either way. I do love Angular and personally loath React, so my opinion is a tad biased but I've been following Meteor and Angular for over a year now and we've all come a long way I can't agree more that we should be more active on the meteor community forums i'm the first person to jump into the Gitter rather than the forums for help since it feels more dynamic. 
I'd also like to thank @Urigo  personally for all the evangelism and coding he's done so far on this. 
Chris
