### ISSUE TITLE
$rootScope._throttledDigest is not a function

### ISSUE THREAD

**Issue by ralphbert** [Urigo/angular-meteor#1126]
I have the following problem. I use the $auth package to wait for the current user in my routes like this:

    resolve: {
        currentUser: ['$auth', function($auth) {
            return $auth.requireUser();
        }]
    }

This fails with the following error:

```
TypeError: $rootScope._throttledDigest is not a function
    at auth.js:27
    at Tracker.Computation._compute (tracker.js:323)
    at new Tracker.Computation (tracker.js:211)
    at Object.Tracker.autorun (tracker.js:562)
    at waitForUser (auth.js:22)
    at requireUser (auth.js:35)
    at Object.$stateProvider.state.resolve.currentUser (routes.js:11)
    at Object.invoke (angular.js:4523)
    at proceed (angularui_angular-ui-router.js:482)
    at invoke (angularui_angular-ui-router.js:478)
```

Any ideas what's going wrong here?
Thanks!

**Comment by anymos** [comment]
+1, I have the same issue, it s not happening each time on my case, only when there is a loginIn in progress

**Comment by introrse** [comment]
I had the same bug, but when I upgraded to the latest version of angular-meteor it went away.  

Just before that I had the suspicion that throttledDigest() was supposed to run the $digest angular inner loop at some limited frequency, but didn't test it before the upgrade.  Good luck!

**Comment by Urigo** [comment]
@ralphbert does it happen to you with 1.3.5?
if so, does it happen to you with the current [master](https://github.com/Urigo/angular-meteor/issues/1105#issuecomment-179228637)?

**Comment by Urigo** [comment]
@ralphbert `angular@1.3.6-beta.1` and `angular-meteor-auth@0.2.0-beta.1` was released.
Can you please test that it's working for you with the new API - http://www.angular-meteor.com/api/1.3.6/auth

**Comment by ralphbert** [comment]
Sorry for the late response!
Yes, with the newest version it is working. Thank you :-)

**Comment by mattiLeBlanc** [comment]
Sorry, but is `$auth.requireUser` removed from the $auth package??
You can't just add and remove functions with each release, I am using this stuff for production purposes (and I love it). But after an update I hate to see my app break.

Looking at the doc, `awaitUser` doesn't seem to be a replacement for `requireUser`.
I just need to resolve the current user in my UI-router and this was the correct function for it.

What to do best?

**Comment by ThomsC** [comment]
+1

**Comment by NiveditN** [comment]
I am facing the same issue as mattiLeBlanc. $auth.requireUser() is not working anymore and my entire app is down. I will have to revert to version 1.3.5 because using the ($q) method does not work well with latency. 

Would really appreciate if you bring back $auth.requireUser() or its equivalent. Otherwise, I'll have to stick to older version. Thanks.

**Comment by mattiLeBlanc** [comment]
I can't seem to revert back to 1.3.5. I even removed the cached packages in
the hidden folder of my home for.
This is a pretty big issue for me.
Hope it is possible to make a quick fix for this?

**Comment by kamilkisiela** [comment]
@mattiLeBlanc You can specify versions in `.meteor/versions`:

```
angular@1.3.5
angular-meteor-data@0.1.0
```

If it still updates to 1.3.6 then probably some package requires `1.3.6`.

**Comment by Urigo** [comment]
Hi everyone.

You are right.

It is my problem that I counted on others to make sure `0.1.0` was still compatible with `1.3.6` and I haven't tested it myself.
Once I did that, I saw your problems instantly.

So, I've released `angular-meteor-auth@0.2.0` now with the old code and the fix so you can keep using the old API with 1.3.6.
I've brought back the old code in a branch and fixes and released it [there](https://github.com/Urigo/angular-meteor-auth/commit/074a4a7742e99b857040be6eba18aad622b43da1).

Please let me know if that is working for you and if not I will keep fixing things on that branch.

As for the new API, `$$Auth.$awaitUser` is suppose to do everything that the old API provides but as I've tested it now, it also has a bug.
It assumes that context of `this` inside is a `scope` but when you use it outside of scope like in a resolve function, it doesn't behave right (@DAB0mB @ozsay).  
I will solve it later and release it as `1.0.0` to mark it clearly as a breaking change.

This is another really bad example of releasing something before testing it completely with a very simple scenario.

Sorry for that and I will improve.

**Comment by mattiLeBlanc** [comment]
@Urigo 
Hi, thanks for picking this up quickly. I guess that is the downside of maintaining a popular package, people start to rely on it :).
It would be good to have some release strategy because updating with packages with Meteor goes so easily, it updates all packages automatically and it introduces issues like this where a rollback seems to be very hard (I didn't manage to go back to 1.3.5 lol ).

Anyway, I updated again and tested the `requireUser()` function in the ui-router resolve.
I noted an error `TypeError: this.$rootScope is not a function` this function is called just after login.
But when I manually go to a private (login required page) it is resolving correctly. 
So I will try one of the other functions that are available:
```
_throttledDigest: ()
getUserInfo: ()
requireUser: (c)
requireValidUser: ()
waitForUser: ()
```

**Comment by mattiLeBlanc** [comment]
I am kindo'ff in big trouble. We need to give a demo tomorrow and my app is broken right now because otf the rootscope issue.
I worked around with using $q in the resolve but that is not always resolving the user correctly.
So I need to try to hack around it today and find a solution to make the demo work today.

**Comment by NiveditN** [comment]
+1 @mattiLeBlanc and I are in a similar fix here. Same issue is happening with me, and we also have a project to deliver. I have again had to revert to 1.3.5. I am facing some other issues in 1.3.5 and there are no docs available for that version -- so I had hoped to be able to update to 1.3.6 such that I can at least know for certain which functions are available for use.

**Comment by Urigo** [comment]
@mattiLeBlanc @NiveditN please try `angular-meteor-auth@0.2.1` and let me know if the problem is solved.

**Comment by mattiLeBlanc** [comment]
@Urigo Yes, it seems to be working. No weird behaviour yet. The Rootscope issue is definitely gone and I am not having any issue using it in the resolve.
Thans for your good work!  You are champ.

With the `waitForUser` in the ui-routers resolve, is there anyway we can do that AUTH_REQUIRED thing you do in your tutorial (using the $q promise)?

**Comment by Urigo** [comment]
for that you should use `requireUser` or `requireValidUser`

**Comment by mattiLeBlanc** [comment]
Yep, working like a charm.

**Comment by NiveditN** [comment]
Just updated and it's working perfectly great! Thanks so much for your quick response! :)
