### ISSUE TITLE
Right usage of helpers or is it a bug

### ISSUE THREAD

**Issue by sauliuni** [Urigo/angular-meteor#1135]
Im having problems understanding how i need to use helpers, since the info outputs in console are misleading.

My use case: Im getting a cursor from a collection, and i extend it (similar to project) with a special attribute, that is needed to use jsTree:

```javascript
this.helpers({
            tree: function () {
                return Trees.find().map(function(elem){
                  return _.extend(elem,{text:elem.description}); //add additional field
                });
            }
        });
```

Later in view i pass the 'tree' to the jstree (as e.g. vm.tree). If i preview this on chrome 47, the jsTree can build up the components, but in the console i get following Information:

```defining 'tree' value helper, note that this feature will be deprecated in 1.4 in favor of using 'getReactively' ```

If i run it on Safari or Firefox, the tree is not build up, i get the same Information and additional one:

```[Warning] overriding 'tree helper' (angular-meteor-data.js, line 1853) ```

What im doing wrong or is it a bug?

**Comment by saulide** [comment]
Seems to be simmilar to https://github.com/Urigo/angular-meteor/issues/1110

**Comment by dotansimha** [comment]
Hi @sauliuni 
The return value of the helper function should be Cursor in order to create the **function** helper you wish to create.
In this case, the return value of `Trees.find()` is a `Mongo.Cursor` which is great, but running map will return another return value (`Array`) so in this case, you will create a **value** helper. 
If you wish to do some of your own logic to the return values, use `transform` method for the `Mongo.Collection` object, as described in http://docs.meteor.com/#/full/mongo_collection . 

Please re-open if you have another questions... good luck!
