### ISSUE TITLE
Angular 1.5

### ISSUE THREAD

**Issue by DrDanRyan** [Urigo/angular-meteor#1159]
I know there are some breaking changes in Angular 1.5, but I am eager to start using the new `component` directive. Is angular-meteor going to start using 1.5 soon after it is released, or is there a plan to take it slow because of the breaking changes?

Is there an easy way to swap out the angular dependency and give it a go before the project officially switches it's dependency?

**Comment by dotansimha** [comment]
You can use it right now, it already published in Atmosphere. 
In order to use it right now, you need to update `angular:angular` package manually:
````
meteor add angular:angular@1.5.0
````

You might also need to update some packages that uses `angular:angular`, such as `angular:angular-sanitize` and other extensions of Angular, so use the same command.

Note that when Meteor release it's new version, 1.3, you'll be able to install angular versions straight from NPM instead of Atmosphere.

**Comment by DrDanRyan** [comment]
That's great! Thanks for the help.
