### ISSUE TITLE
Any other way to update easily?

### ISSUE THREAD

**Issue by berkaey** [Urigo/angular-meteor#1182]
hey after a day trying to figure how can update a document with the new api. I did this
```
	$reactive(this).attach($scope)
	
	$rootScope.$watch "Schemas", (n,o)->

		$scope.subscribe "settings" 
		, ()-> 
			return []
		, ()-> 
			if Settings.find().fetch().length is 0
				Settings.insert({slug:slug})

		$scope.helpers
			settings: =>
				return Settings.findOne {slug:slug}

		$scope.$watch "settings",(n)->
			console.log n
			if n
				$rootScope.form = 
					data:$scope.settings
					schema:$rootScope.Schemas.Settings
					button:".save-settings"

	$rootScope.saveSettings = ()->
		update = $scope.settings
		id = update._id
		delete update._id
		Settings.update({"_id":id},{$set: update})
```

with old api I could do this in few lines with autobind etc. in this case, is my approach is correct or what should I do?

**Comment by Deadly0** [comment]
@berkaey if you asking about this line ```Settings.update({"_id":id},{$set: update})``` than yes, it's  correct approach.

**Comment by berkaey** [comment]
I mean the whole thing. for example while subscribing I cant give null to second paramater so it could be more readable or like before is there a way to autobind things? and also I cant save before removing the id from updated obj. is it happens to me only or is this also normal?

**Comment by Deadly0** [comment]
@berkaey in most cases you no need to use $watch and onReady handler, but i cant suggest you anything because not enough code published. What is ```Schemas``` and ```slug``` ? Why do you use ```$rootScope```. Why do you use ```$reactive(this).attach($scope)``` and ```$scope``` together?

**Comment by berkaey** [comment]
this is a code from a private meteor package and the real app has the Schemas obj. and when it loaded. it should trigger this so $scope.form be filled with necessary information. I'm using $rootScope because now $scope has the settings object so I need to trigger that saveSettings in some other view so I use it like this. 

basically I wanted to do
1. Get Settings with specific "slug" (it is like username for settings and there is only one.)
2. If no doc. create one.
3.When everything is ready ($watch), pass the settings obj. to $rootScope.form (this is a form so when I change something in that obj. it should update it)
4. Save the data.(for ex. I still couldn't the way to save like 3-way binding )

so what is the best practise of this? the old api was understandable and act like it should be I guess, but I understand why angular-meteor choose this path.

**Comment by dtruel** [comment]
Hello,

It looks to me like in the old api, angular-meteor was smart enough to figure out what to do to update the object so that it matched the server. In the new api, you have to manually tell it what to update.  Is this right?

If so, this is a significant regression in my humble opinion.  I've built my app in a generic way that depends on angular-meteor being able to figure out what to do to update the object.  It is a very flexible application that doesn't necessarily know what the object is going to look like.  I think that is a strong point for my application that makes it great.  However, it depends on angular-meteor being able to figure out what to update.  I do not want to be stuck using an unsupported version of angular-meteor.  Is there a way that the functionality that figures out what needs to be updated and does it automatically could be brought back?  I am missing the .save() functionality that was so nice.  Thank you for a great library!

**Comment by Urigo** [comment]
with version `1.3.9_2` we've removed the deprecation warnings by default so that you could continue using the old API as long as you wish.
The new API is still recommended because it's more compatible with the rest of the Meteor community and is also more robust and performant.
But I understand your point and that's why I've removed the messages.
Also now there is much more documentation on the new API

**Comment by dtruel** [comment]
Awesome, thank you so much @Urigo.  You've done great work with this library and I appreciate you listening to everybody.  I agree with you that the new API offers a lot in terms of compatibility, but leaving this in is a real help to me.  Many thanks.
