### ISSUE TITLE
Try to remove the need of angular-babel in Meteor 1.3

### ISSUE THREAD

**Issue by Urigo** [Urigo/angular-meteor#1192]
Try to add all the features angular-babel has to the official ecmascript package so that we won't need to add it anymore in Meteor 1.3.
If not released in Meteor 1.3, update angular-babel to use the latest Babel as similar as possible to Meteor's.

Need to add "es7.decorators" and add babelHelpers like in here: https://github.com/Urigo/angular2-meteor/blob/feature/meteor1.3/tests/packages/babel-runtime/babel-runtime.js#L277-L337

Also related:
https://github.com/meteor/meteor/issues/6028
https://github.com/meteor/meteor/issues/6057

@pbastowski @kamilkisiela

**Comment by pbastowski** [comment]
@Urigo 

We could also recommend that people use TypeScript instead of `angular-babel` / `ecmascript` packages, because:

1. it already supports Decorators, and 
2. in most cases TypeScript can be used as a direct drop-in replacement for Babel (this is especially easy if the user does not care about type checking, just transpiling to ES5)

People would have to use the `.ts` extensions instead of `.js`, but that's about it. I have replaced Babel with TypeScript in one of my production apps without any side effects. I see this as a viable option.

Do you think this is an option?

**Comment by Urigo** [comment]
@pbastowski that's a good idea.
I think we should provide the 2 options though, and specifically make the ES2015 option easier.

On the Typescript point, what package do you use today?  please have a look at this discussion about adding an official `typescript` package - https://github.com/Urigo/angular2-meteor/issues/102

**Comment by pbastowski** [comment]
I agree, that Meteor's own ecmascript package should either provide decorators by default or allow us to easily add optional Babel components.

As far as typescript goes, I use my `pbastowski:typescript` package in my projects. It works exactly the same as my angular-babel package, except that it uses the TypeScript compiler instead of Babel. Also, it does not ng-annotate, but I think we don't need ng-annotate any more, especially if users use my angular2-now library, which includes injection into classes.

So, whose typescript package will be the one to rule them all :)  ???

**Comment by Urigo** [comment]
About Typescript - look in the [issue](https://github.com/Urigo/angular2-meteor/issues/102) - this one - https://github.com/barbatus/ts-compilers

**Comment by mgrivera** [comment]
Hi @pbastowski, 

If we start using typescript in 1.3 as you suggest, and I will be glad if we could, are we going to miss the source mapping mechanism that we have right now? You now this is a big issue for me! And you helped me to solve this issue in the current version. 

I mean: are we going to "see" our typescript code in chrome debugger (or just the transpiled one)? 

Thanks and bye ...

**Comment by dotansimha** [comment]
I think we can close this issue, since Meteor supports now `.babelrc` (https://github.com/meteor/meteor/issues/6028) and we can solve the issue with the decorators :)
