### ISSUE TITLE
How to pass filter options in new API?

### ISSUE THREAD

**Issue by rclai** [Urigo/angular-meteor#129]

**Comment by Urigo** [comment]
You can send a reactive function instead of a collection in $meteorCollection's first parameter.

You can look at the example here (stickyTodos):
http://angularjs.meteor.com/api/meteorCollection

Or here in the tutorial in step 15:
https://github.com/Urigo/meteor-angular-socially/blob/step_15/client/parties/controllers/partiesList.js#L13

**Comment by catsoft** [comment]
here is a sample for clean understanding :)

 $scope.cities = $meteorCollection(function() {
                    return Cities.find({
                            companyId: $rootScope.currentUser.profile.companyId
                    })
                }, true);

**Comment by Urigo** [comment]
Cool :)
By the way, no need for the last true parameter, true is now the default

**Comment by catsoft** [comment]
yeap my mistake sorry :)

**Comment by Urigo** [comment]
Closing for now, @rclai please re-open if there are more questions

**Comment by rclai** [comment]
Thanks guys.
