### ISSUE TITLE
Angular-meteor tutorial WhatsApp is not working properly in IOS 9.3

### ISSUE THREAD

**Issue by juancho559** [Urigo/angular-meteor#1341]
Hi,
I'm trying to deploy Whatsapp tutorial application shown on this page (http://www.angular-meteor.com/tutorials/whatsapp/meteor/layout) in IOS 9.3, but I'm not able to run properly due to a navigation problem. The behaviour is very weird, you have to click more than one time an action button in order to navigate to other page. Also, the icons in the tab control are not visible.

I appreciate any help.

Thanks!!

**Comment by tomitbe** [comment]
Hi Juancho,

we are dealing with the same issue.
started the tutorial of angular-meteor. as soon as we add ionic, none of the buttons are tappable.
once we double click (tap), the ng-click action is triggered...

**Comment by martinothamar** [comment]
Experiencing the same problem. Substituted `ng-click` with `on-release` for my buttons temporarily.

**Comment by juancho559** [comment]
Hi @tomitbe,
Please add to your watch list this page. I'm going to share a solution there. [No icons - double tap on iOS devices](https://github.com/DAB0mB/angular-meteor-whatsapp/issues/12)

**Comment by tomitbe** [comment]
Done :-)

Met vriendelijke groeten,

Tom


Op 6 mei 2016 om 17:39 heeft juancho559 <notifications@github.com<mailto:notifications@github.com>> het volgende geschreven:


Hi @tomitbe<https://github.com/tomitbe>,
Please add to your watch list this page. I'm going to share a solution there. No icons - double tap on iOS devices<https://github.com/DAB0mB/angular-meteor-whatsapp/issues/12>

-

**Comment by ntoka** [comment]
Is there an official fix to this, @Urigo ? I've seen several issues that describe very similar problem but no official fix, only workarounds ( e.g. https://github.com/Urigo/meteor-ionic/issues/30 , https://github.com/DAB0mB/angular-meteor-whatsapp/issues/12 ). Also - does anyone know whether this issue is also applicable if we're using Ionic CLI instead of Angular CLI?

**Comment by jvillamor-visp-net** [comment]
Has there been any fix on this? double tapping in the IOS is very inconvinient.

**Comment by jgontrum** [comment]
Cannot believe that there is no progress on this bug. Is no-one actually using this project for production?

**Comment by DriesVandermeulen** [comment]
Same problem here!

**Comment by DriesVandermeulen** [comment]
I have Fixed the double tapping issue by removing the ```mobile-experience``` package. This package includes ```fast-click```

From ionic docs: 
```Out of the box, Ionic automatically removes the 300ms delay in order to make Ionic apps feel more “native” like. Resultingly, other solutions such as fastclick and Angular’s ngTouch should not be included, to avoid conflicts.```

The mobile-experience package includes 3 packages:
- fastclick: avoid the 300ms touch delay
- mobile-status-bar: avoid the status bar information covering up your app content
- launch-screen: cover the app with a launch image so that people don’t have to see things loading

After removing ```mobile-experience``` I have re-added the ```mobile-status-bar``` and ```launch-screen```. So everything works like normal.

@Urigo this should be included in the documentation.

**Comment by Urigo** [comment]
Fixed and deployed.
Please open a new issue if the new explanation on the tutorial is not working for you.
thank you so much @DriesVandermeulen

**Comment by lleoooell** [comment]
hello;

still does the bug for me even after removing mobile-experience ;(

**Comment by Urigo** [comment]
@lleoooell can you please share your repo?

**Comment by saratSubramaniam** [comment]
Hey,
My app runs in Angular 2. And it experiences a similar issue only in iOS 9.x. The elements/buttons with (click) attribute bound to it, are not responsive. Out of 10 clicks, one might work.
In desktop browsers and in iOS 10, it has no issues at all.
Any thoughts anyone ?

**Comment by lleoooell** [comment]
@urigo which one?
I don't fork angular-meteor anymore, I'm working on meteor only now...

**Comment by Urigo** [comment]
@saratSubramaniam can you try to see if when you are running only Angular (without Meteor) does it still happens?

@lleoooell if you are not using Angular I think the Meteor repo is the place you should file your issue to
