### ISSUE TITLE
Cannot install angular2-meteor-auto-bootstrap => UNMET PEER DEPENDENCY angular2-meteor@0.6.0

### ISSUE THREAD

**Issue by bel3atar** [Urigo/angular-meteor#1387]
I am following the guide here [https://www.angular-meteor.com/tutorials/socially/angular2/3-way-data-binding](url). 
Reaching the _Binding Meteor to Angular_ step, I fail to run the command to install angular2-meteor-auto-bootstrap.

**Comment by thebigbluebox** [comment]
Here is my package.json and try it and see if it works.

{
  "name": "socially",
  "private": true,
  "scripts": {
    "start": "meteor run"
  },
  "dependencies": {
    "@angular/common": "^2.0.0-rc.4",
    "@angular/compiler": "^2.0.0-rc.4",
    "@angular/core": "^2.0.0-rc.4",
    "@angular/platform-browser": "^2.0.0-rc.4",
    "@angular/platform-browser-dynamic": "^2.0.0-rc.4",
    "angular2-meteor": "^0.5.6",
    "angular2-meteor-auto-bootstrap": "^0.5.6",
    "angular2-meteor-polyfills": "^0.1.1",
    "es6-shim": "^0.35.1",
    "imports": "^1.0.0",
    "meteor-node-stubs": "^0.2.3",
    "reflect-metadata": "^0.1.2",
    "rxjs": "5.0.0-beta.6",
    "zone.js": "^0.6.12"
  }
}

**Comment by numerized** [comment]
Amazing! many thanks!

**Comment by Urigo** [comment]
the tutorial was updated and deployed.
Please open another issue if it doesn't work for you

**Comment by hhkk** [comment]
To clarify/confirm: I had already gotten a project up at the point where I had the issue below.  I copied the package.json file from above and this problem was fixed.

> C:\utd\160802Socially>npm --version
> 3.10.5
> C:\utd\160802Socially>meteor npm --version
> 3.10.5

> C:\utd\160802Socially>npm install
> npm WARN angular2-meteor-auto-bootstrap@0.6.0 requires a peer of angular2-meteor@^0.6.0 but none was installed.
> C:\utd\160802Socially>meteor npm install
> npm WARN angular2-meteor-auto-bootstrap@0.6.0 requires a peer of angular2-meteor@^0.6.0 but none was installed.
> 

BTW Uri - One thing I found a little confusing in the tutorial in step zero, was the indication to do an NPM install.  I wasn't sure why I wouldn't do "meteor NPM install" (perhaps that question is a personal education issue).  Also I thought it would be a little clearer if you highlighted that npm install step in grey. the way you did the other manual steps, so people wouldn't miss it assuming it's required.

Thanks!
H
