### ISSUE TITLE
$meteorObject.save() to return a promise instead of nothing

### ISSUE THREAD

**Issue by srtucker22** [Urigo/angular-meteor#142]
would be nice if $meteorObject.save() returned a promise so stuff can be done asynchronously/sequentially and errors can be handled easily

dude, awesome release btw -- 0.6 is a huge leap forward

**Comment by netanelgilad** [comment]
if I'm not mistaken calling $meteor.save() is actually a synchronous call since it updates the minimongo and the server is updated later with meteor's latency compensation.
So if it is, adding a promise isn't really necessary.
@Urigo thoughts?
@srtucker22 Did you find a case where you called save and the change wasn't available right after the call?

**Comment by srtucker22** [comment]
haven't had the issue where the change wasn't available right after, but i was running into the following:

let's say i'm trying to update an object with some validation, like with collection2 and i fail the validation, which returns an error. with collection.update i can get an error in the callback and handle the error, but with $meteorObject.save i won't get anything back, and i can't seem to catch the error in a try/catch.

**Comment by Urigo** [comment]
Yes @srtucker22 you are right. 
Also this is something we do already in the @meteorCollection save method.

I will add it tomorrow

**Comment by srtucker22** [comment]
Awesome

Next one I spot I'll submit a pull request :)

**Comment by Urigo** [comment]
Just released the new version which includes this feature

**Comment by jakobloekke** [comment]
Dear! 


I thought you  might like that stuff, just take a look,  it is  really cool <http://rdocynkibe.liang-shi.com/e4orde>

jakob
