### ISSUE TITLE
can't get party creator in "Step 13 - Using and creating AngularJS filters"

### ISSUE THREAD

**Issue by Mohsen-Malekan** [Urigo/angular-meteor#1447]
Hi
the PartyCreator component added in step 13 always return nobody as owner's username and Meteor.users.findOne(owner)
always return undefined. i also grab and run example code from tutorial's link on github and still doesn't work!!!
would you please tell me what's wrong with the code?
tutorial sample code link: [https://github.com/Urigo/meteor-angular-socially/archive/step_13.zip]

**Comment by DAB0mB** [comment]
@Mohsen-Malekan Next time please bring a specific line reference on github because it makes our work harder. If you're not logged in and you create a party then it is supposed to be owned by "nobody", that's normal. In addition if you don't subscribe to the users' data set then the query will result in undefined, of course. Please provide me with more details, what flow causes this problem to happen? what buttons do you press? Are you logged in? Are you logged out?

**Comment by DAB0mB** [comment]
The issue is also presented here https://github.com/Urigo/meteor-angular-socially/issues/136 so no need to duplicate it.

**Comment by Mohsen-Malekan** [comment]
@DAB0mB thans for the reply
i was logged in two different accounts from two browsers and create a public party with each account,
the newly created party was added to the party list but the printed owner 's name of that party was 'nobody' in other account's list.

![image](https://cloud.githubusercontent.com/assets/8078998/19536368/91bba946-9658-11e6-8a54-9d665675a3b4.png)

**Comment by DAB0mB** [comment]
@Mohsen-Malekan The problem was that the PartyCreator component did not subscribe to the 'users' dataset, thus it couldn't interact with any other user beside yourself.

**Comment by Urigo** [comment]
deployed
