### ISSUE TITLE
Moving ng2-admin akveo template on meteor-angular2 app 

### ISSUE THREAD

**Issue by PopPushOut** [Urigo/angular-meteor#1509]
Greetings everyone,

Here is some background. Me and small group of people are making a project, we are really interested in synergy between angular2 and meteor. We would like to create a big project using it. I want to implement Angular2 template on angular-meteor app;

I found ng-2 template here: https://github.com/akveo/ng2-admin
here is the link how to quick start it using npm:
https://akveo.github.io/ng2-admin/articles/002-installation-guidelines/
I would love to know the idea how to put whole template structure on a meteor-angular2 structure.

Now I tried to add packages from template to raw meteor-angular2 project, after fixing plenty of problems I got dozens more. It seems it doesn't work my way.
 
The structure of template is totally different and there is plenty npm packages used in it which I have no idea how works together with meteor. 

I found similiar question related to my problem in meteor forum but nobody responded with an solution. 
https://forums.meteor.com/t/how-to-integrate-meteor-to-an-existing-angular-2-project/30606

**Comment by dotansimha** [comment]
Few months ago I tried to use this admin panel inside angular-meteor project. I no longer have the code, but here are few guidelines:
1. Almost all files should move under /imports/ because of Meteor's files structure.
2. Make sure to load all CSS files into their component, but you can start with a big SCSS file that imports all of them, and later encapsulate each style into it's Component.
3. I remember that the template path had an issue and I needed to fix almost all of them.

I recommend to open an issue in the template's maintainer in order to get real support for Meteor environment. 

The issue is not related directly to `angular2-meteor`, because it's a issue with the implementation and file structure.

**Comment by pedrolucasoliva** [comment]
and you got it @dotansimha ?

**Comment by dotansimha** [comment]
@pedrolucasoliva , yeah, I had to make some modifications in order to make it work... most of them related to file structure and path changes.

**Comment by pedrolucasoliva** [comment]
Pretty cool @dotansimha! I will do it too and realise at git. Can you fork this project?

**Comment by PopPushOut** [comment]
Thanks for an answer, I would be also really happy if you could share the template made on meteor. Thanks in advance.

**Comment by gntlman-bstrd** [comment]
Could you please provide either the source or the steps you took to convert the template into the angular2-meteor structure?

**Comment by juniorsml** [comment]
Hi everyone. Have someone the link to a repository with the meteor code?

**Comment by Slavrix** [comment]
Did anyone ever end up getting the admin page to work with meteor?
