### ISSUE TITLE
Whatsapp2 tutorial needs to start with an explanation for Ionic or an overview of the tutorial

### ISSUE THREAD

**Issue by LJNielsenDk** [Urigo/angular-meteor#1560]
The whatsapp2 tutorial needs to start with an explanation for Ionic or an overview (what are we learning and when) of the tutorial to seem more relevant.

I started following the tutorial because I want to learn Angular2 and Meteor. So far I made it to the "TypeScript Interfaces section" of https://angular-meteor.com/tutorials/whatsapp2/ionic/chats-page and my main unanswered questions that I really wish the tutorial would have answered by now are:

- Why is so much of this about Ionic, that's not what I came here for?
- When will we get to the things I actually came here for and is there even enough of it here to make it worth bothering to continue following the tutorial?
- If I'm not planning to use Ionic myself will this tutorial even be all that useful to me?
- Will I need to use Ionic and if not why is there so much of it here?

That's way too far into the tutorial to still be dealing pretty much only with things you didn't come to the tutorial for and which the reason for and inclusion of hasn't been explained yet.

**Comment by minau87** [comment]
I agree, although I haven't tried the new Whatsapp Clone tutorial myself, only read through it.

Recently I tried to look up some things on how to work with Meteor now that they introduced meteor/rxjs (I approached Meteor earlier, when meteor/rxjs wasn't a thing yet) and all of a sudden there's a new tutorial, which - in my opionion - shifted it's focus from purely Meteor previously to now Meteor + Ionic.

I think [this](https://angular-meteor.com/tutorials/socially/angular2/bootstrap) might be more of what you're looking for, although it's not being maintained any longer (It's kind of up to date from what I can tell).

From my point of view, as much as I appreciate Meteor and all the work they put into it, it was a very poor decision to no longer maintain the Socially tutorial and focus so heavily on the Meteor + Ionic tutorial.
The wiser choice might have been to keep both of these tutorials (and thus targeting the people who only want to learn Meteor + Angular 2, aswell as those who are interested in Ionic), although I understand that it's probably a lot of work to keep both of 'em up to date.

It's kind of frustrating having to deal with Ionic additionally, even though I'm really just interested in learning Meteor + Angular 2.

**Comment by Urigo** [comment]
I agree as well.
I hope to start on this on the weekend

**Comment by minau87** [comment]
Woah, @Urigo, the man, the myth! :)

No worries man and thank you very much for your effort, you're doing awesome work here  and I think I'm speaking for a lot of us when I say this.

If you don't mind, I have a suggestion for your tutorial:

Add a section where you showcase how to use MeteorObservables from within an Angular service. I think it would be a good idea to have an example that shows how to do it, since that's (that in this case being the loading of data) an approach recommended by Angular. I saw in your current tutorial somewhere that there indeed is an example, but it uses Promises instead of Observables if I'm not mistaken.

I'm currently trying to figure it out myself, as you can see [here](http://stackoverflow.com/questions/42278474/how-to-use-meteor-rxjs-within-an-angular-2-service), but sadly I had no success until now.

Now, I'm not a experienced dev, I'm only trying to code as a hobby of mine, but im pretty certain a lot of people would highly appreciate such an example.

Let me know if you consider it. ;)

Keep being awesome and thank you very much!

**Comment by cyberbeast** [comment]
Agreed. Having separate tutorials for 
1. angular2 + meteor
2. ionic + meteor
would probably expose learners to different concepts applicable in use-cases for these.

Looking forward to more tutorials.

@Urigo Thank you for all your hard work. :)

**Comment by irongollem** [comment]
I just learned about Meteor from a colleague, so was looking to get into it. I kinda agree with @LJNielsenDk  that as I don't really know everything here yet I'm kinda surprised bout the ionic stuff. (will want to do the mobile part with NativeScript or service workers if possible although I must say I dont know ionic yet.)

Nice to see this is so active still :). @Urigo nice talks on youtube!

**Comment by minau87** [comment]
@irongollem If you just learned about Meteor, looking into their older [tutorial](https://angular-meteor.com/tutorials/socially/angular2/bootstrap) might be a good idea. I think this one, although it says it's deprecated and no longer maintained, is a better entry point to understand the basics behind Meteor itself, which are then applicable to whatever learning projects you are working on. Helped me a lot.

**Comment by Urigo** [comment]
I've started re-writing the intro to the tutorial, did a first try here: https://angular-meteor.com/tutorials/whatsapp2-tutorial
Let me know if that makes sense as an intro

**Comment by thoni56** [comment]
I totally agree with the sentiments of the OP here. I was looking to learn Meteor primarily, went to checkout the Ionic-flavoured tutorial, tries a few steps. And for me, as a novice to JS frameworks, I was totally put off by the sheer abouts of things that I had to type which I just didn't understand. And might have never come back...

A few days later, I bit the bullet, and although announced as deprecated, I ventured on the Meteor+Angular tutorial. I'm now down to styling, and have learned huge amounts and learned to love Meteor!

The 'legacy' tutorial has much better progression IMHO for a beginner like me. It's so much easier to get started with and it introduces concepts a more pleasant pace, e.g. styling at the end, where it belongs, in a tutorial for an application framework.

It's also very simple to setup, just compare to the number of lines of commands and code that need to be performed in the Ionic version, before you even can see any progress. With the legacy tutorial it's just a few lines and you have a first running version.

Just my $0.02.

Thanks anyhow for creating these tutorials! It makes it so much easier to learn Meteor, and shows off its features in a way reading documentation could never do!

**Comment by Urigo** [comment]
thank you all for the feedback!

I've been working on a structure that I think will be both easy for beginners, good for advanced developers and also pretty easy to interchange technologies (Angular Material or Ionic, Meteor live query or GraphQL, etc...).

If anyone wants to help me with this so I could get an early feedback and put it out there as fast as possible, feel free to email me.

About changes, don't worry, as you can see, we have versions of the tutorial now and nothing will be deprecated anymore. all new versions will still include the former tutorials and a git diff comparing the versions in case you want to update and want to know exactly what to do

**Comment by Urigo** [comment]
We've done a lot of updates in the last month.

we've published new [angular-compilers package](https://github.com/Urigo/angular-meteor/tree/master/atmosphere-packages/angular-compilers) that supports all the features the Angular CLI gives you:

- Typescript compilation
- Assets compilation (HTML, styles)
- Angular's AoT compilation
- Rollup's bundling with Tree Shaking

and added a lot of examples with for all those features plus an example with Angular CLI if you want to use it instead of the Meteor CLI:
https://github.com/Urigo/angular-meteor/tree/master/examples

We've also updated all the latest versions including the latest Angular 5 RC and Meteor 1.6.

Please open a new issue if you encountered one.

We've updated the Ionic CLI tutorial and in the process of updating the Meteor CLI one.
