### ISSUE TITLE
styles like .less .css or scss dont work fine in angular-meteor

### ISSUE THREAD

**Issue by HectorRPL** [Urigo/angular-meteor#1562]
Remember, an issue is not the place to ask questions. You can use [Stack Overflow](http://stackoverflow.com/questions/tagged/angular-meteor) for that, or you may want to start a discussion on the [Meteor forum](https://forums.meteor.com/).

Before you open an issue, please check if a similar issue already exists or has been closed before.

### When reporting a bug, please be sure to include the following:
- [x] A descriptive title
- [x] An *isolated* way to reproduce the behavior (example: GitHub repository with code isolated to the issue that anyone can clone to observe the problem)
- [x] What version of `angular-meteor` you're using, and the platform(s) you're running it on
- [x] What packages or other dependencies you're using
- [x] The behavior you expect to see, and the actual behavior

See [here](https://github.com/meteor/meteor/blob/devel/Contributing.md#reporting-a-bug-in-meteor) for more detail on what is expected of a bug report.

### When you open an issue for a feature request, please add as much detail as possible:
- [ ] A descriptive title
- [ ] A description of the problem you're trying to solve, including *why* you think this is a problem
- [ ] An overview of the suggested solution
- [ ] If the feature changes current behavior, reasons why your solution is better

I've been working with angular meteor for 1 year and then I have this problem 

I think there is a bug with the .less angular components in meteor because in many cases the styles work, but when we press F5 the styles are not respected.

I have followed the few steps that come in angular-meteor tutorial without good results.
I search in stackoverflow and meteor forurm but no much people usin angular-meteor, or maybe almos all using angular-material, I dont know

I bought a template (inspinia) in wrapbootstrap, which works in angular 1, angular 2 and meteor. All three are perfectly executed and all styles work well.
The problem is when I want to use the template in meteor using angular is a very serious problem since the styles work poorly.

What I've tried:

All in main.less
I copied all the code from the template's style.less file into the main.less folder
The result is that it does not take all styles, varying in color, among many other things.

Copy the style.less into node_modules
Create a folder in node_modules with a .less file of all template styles (approx 9000 lines) and import it from main.less in this way
Import 'inspinia / style.less';
It is the "best" solution so far, however it has two drawbacks:
1) However there are only some styles that do not work such as radio buttons and check box among others.
2) I had to do it manually in node_modules, surely at the time of deploy I will have many problems.
3) It is an uncool method.

Copy everything in main.less with! Important in every statement
Many styles are taken, but at the moment of changing screens some styles continue to appear. Even comes to decompose the footer.
Checkbox styles and radio buttons, among others, do not work.
Some elements like the footer are descoponene and sometimes there are colors where they should not be.

Then I have tried everything, separated, compose, folders, even tried to import the styles as if it was only using meteor and works only in the middle, because at the time of refreshing the page styles are lost.

What should I do? Why .less, .sass. Css. Scss works poorly with meteor angular-meteor?
Why are styles not respected?

What is the best way to import styles within angular-meteor?
Please do not tell me to see the tutorial angular-meteor section .less because it only works halfway.

Please help

**Comment by minau87** [comment]
One thing I'd like to add:
In an earlier version of Meteor, you could apply changes to your .scss-files located next to your components without the changes triggering the entire application to reload.
I'm not sure if I'm missing something here (might aswell be intended/expected behaviour - I'm not experienced enough to tell), but this behaviour is reproducible with the meteor-base.

**Comment by Urigo** [comment]
we've published new [angular-compilers package](https://github.com/Urigo/angular-meteor/tree/master/atmosphere-packages/angular-compilers) that supports all the features the Angular CLI gives you:

- Typescript compilation
- Assets compilation (HTML, styles)
- Angular's AoT compilation
- Rollup's bundling with Tree Shaking

and added a lot of examples with for all those features plus an example with Angular CLI if you want to use it instead of the Meteor CLI:
https://github.com/Urigo/angular-meteor/tree/master/examples

We've also updated all the latest versions including the latest Angular 5 RC and Meteor 1.6.

Please open a new issue if you encountered one.
