### ISSUE TITLE
Meteor test doesn't work

### ISSUE THREAD

**Issue by GuofuHuang** [Urigo/angular-meteor#1587]
I'm trying to write some test functions to test the app I created, but it doesn't run any test files. 
I use the command to test: 'meteor test --driver-package practicalmeteor:mocha'
![screen shot 2017-03-28 at 2 42 14 pm](https://cloud.githubusercontent.com/assets/10643064/24424590/b5253c30-13c6-11e7-8157-62b227e6b036.png)

Does anybody know how to solve this?

**Comment by dinigo** [comment]
+1

**Comment by ardatan** [comment]
We've updated Angular Meteor Compilers with a lot of changes, and practicalmeteor:mocha test driver has an old version of mocha, so zone.js cannot patch this version of mocha. You need to use ardatan:mocha package instead of practicalmeteor:mocha.
You can look at the example below;
https://github.com/Urigo/angular-meteor/tree/master/tests/angular-compilers-tests
If you still encounter this issue, please open a new issue.
