### ISSUE TITLE
Scss compiler error

### ISSUE THREAD

**Issue by urco** [Urigo/angular-meteor#1593]
Im following the tutorial  but Im getting the next error when I try to run for first time the App 
```
While processing files with angular2-compilers (for target web.browser):
/client/main.scss: Scss compiler error: File to import: {}/node_modules/ionic-angular/components/typography/typography not found in file: components
```

**Comment by ghybs** [comment]
Hi,

See https://github.com/Urigo/Ionic2-MeteorCLI-WhatsApp/commit/da6ccca1224add19fb7491444c138574099a39f4#commitcomment-21553512

**Comment by Urigo** [comment]
we've published new [angular-compilers package](https://github.com/Urigo/angular-meteor/tree/master/atmosphere-packages/angular-compilers) that supports all the features the Angular CLI gives you:

- Typescript compilation
- Assets compilation (HTML, styles)
- Angular's AoT compilation
- Rollup's bundling with Tree Shaking

and added a lot of examples with for all those features plus an example with Angular CLI if you want to use it instead of the Meteor CLI:
https://github.com/Urigo/angular-meteor/tree/master/examples

We've also updated all the latest versions including the latest Angular 5 RC and Meteor 1.6.

Please open a new issue if you encountered one.
