### ISSUE TITLE
Upgrade package dependencies

### ISSUE THREAD

**Issue by staeke** [Urigo/angular-meteor#1594]
Currently requires angular@^2.0.0 (but angular is up to 4)
Currently requires angular2-meteor-polyfills@0.1.1 (but is up to 0.2.0)

**Comment by Urigo** [comment]
we've published new [angular-compilers package](https://github.com/Urigo/angular-meteor/tree/master/atmosphere-packages/angular-compilers) that supports all the features the Angular CLI gives you:

- Typescript compilation
- Assets compilation (HTML, styles)
- Angular's AoT compilation
- Rollup's bundling with Tree Shaking

and added a lot of examples with for all those features plus an example with Angular CLI if you want to use it instead of the Meteor CLI:
https://github.com/Urigo/angular-meteor/tree/master/examples

We've also updated all the latest versions including the latest Angular 5 RC and Meteor 1.6.

Please open a new issue if you encountered one.
