### ISSUE TITLE
ObservableCollection  can't trigger callback in client when insert/update

### ISSUE THREAD

**Issue by magicboy110** [Urigo/angular-meteor#1597]
According to the document description : https://angular-meteor.com/api/meteor-rxjs/latest/ObservableCollection#Collection+insert

ObservableCollection.insert() will return a Observable object witch will trigger complete callback when the operate complete.

It's truth running  in server, but in client, the complete will not trigger never.

Is this a bug ?

**Comment by jerradpatch** [comment]
I have been using it for a while, and I dont think its a bug. I think its because is observing the local collection and it cannot be sure when a server pushes new data, so it always watches it. If you are looking for a completion like a promise try .take(1) which will unsubscribe after 1 item is recieved.

**Comment by gh0st** [comment]
@jerradpatch I was looking to take advantage of this callback too. I just need a unique way of identifying the record that was added with the `insert()`.

**Comment by jerradpatch** [comment]
If your looking for a completion, I think the best that you will get is a signal when the local and the remote are in sync. But that will only give you up to that point and not after. In order to do that you have to put a observable inside the callback to the .subscribe() method on the collection (when you telling the server which models to send to the local, it takes a callback). I created a wrapper method that would both subscribe to the remote and the local using a Subject. Another way would to specifically send a completion to whoever subscribed. You can do this in the server side subscription using this.onRead() method. But be aware the client subs will not continue to to receive notifications, unless you resub in the on complete. Hope this helped.

**Comment by gh0st** [comment]
@jerradpatch no not looking for a completion, just need an _id equivalent to what will actually end up in the db after everything gets synced.

**Comment by jerradpatch** [comment]
I am just going to take some guesses since i donno an _id equivalent unless you create the Id yourself. If you only want unique results returned in a query then look at distinct() from rxjs lib. I would stay way from projections as you endup with a lot of partial data in the local. If your logic is following the concept of synchronous. Then well thats the wrong way with rxjs. There really is no synced, there are just continuous streams that are tapped into. If you would please explain what feature your working on and why you need the unique list when synced and I can better help?

**Comment by gh0st** [comment]
So given [this](https://docs.meteor.com/api/collections.html#Mongo-Collection-insert) document from Meteor's Mongo.Collection 

> insert will generate a unique ID for the object you pass, **insert it in the database, and return the ID**. When insert is called from untrusted client code, it will be allowed only if passes any applicable allow and deny rules.

That's all I'm really after @jerradpatch

**Comment by jerradpatch** [comment]
Aww man, you can gen your own id with mongo.objectID() and that will be used as the same key saved in the DB. As for the allow deny rules, you should checkout the built in accounts package.

**Comment by gh0st** [comment]
Ya sort of, but I don't have a `mongo` object, I have a `MongoObservable.Collection` which I invoke `.insert()` on.

**Comment by jerradpatch** [comment]
Mongo is a class that comes in a package installed with meteor (I believe)
. import { Meteor } from 'meteor/meteor'; and then let id =
Mongo.ObjectID();
Its part of the collections https://guide.meteor.com/collections.html

**Comment by jerradpatch** [comment]
Yeah, type "meteor list" in the terminal and you will see "mongo" listed.

**Comment by jerradpatch** [comment]
One other thing to add, is dont forget to install the types.

add these to the tsconfig file

"types": [
  "meteor-typings",
  "@types/meteor"
]

and the same in your npm package ex:
meteor npm install --save-dev meteor-typings

**Comment by ardatan** [comment]
There is no callback in meteor-rxjs, it returns observable so you can subscribe it to
