### ISSUE TITLE
Using templateUrl and styleUrls hangs up the app.

### ISSUE THREAD

**Issue by Deadly0** [Urigo/angular-meteor#1599]
Using `templateUrl` and `styleUrls` in component meta data hangs up the app.

```
@Component({
	selector: 'app',
	templateUrl: './app.component.html',
	styleUrls: ['./app.component.scss'],
})
export class AppComponent {
	constructor() {

	}
}
```
But `templateUrl` and `styleUrls` is the recomended by angular team way to import html/css.
The error in the console `ERROR RangeError: Maximum call stack size exceeded`
What am i doing wrong?

angular2-compilers 0.6.6
angular 4.1.2
platformBrowserDynamic

PS 
```
import template from './app.component.html';
import style from './app.component.scss';
```
Works well

**Comment by rrubio** [comment]
@Deadly0 I came across the samething, i ended up using the import method and works perfectly. From what i gather, it's particular to meteor, but aside from that works perfectly.

**Comment by Deadly0** [comment]
@rrubio thx, i use the same way too. But `templateUrl` and `styleUrls` functionality not working :(

**Comment by briancvn** [comment]
I have same problem, the functionality still not working

**Comment by Urigo** [comment]
we've published new [angular-compilers package](https://github.com/Urigo/angular-meteor/tree/master/atmosphere-packages/angular-compilers) that supports all the features the Angular CLI gives you:

- Typescript compilation
- Assets compilation (HTML, styles)
- Angular's AoT compilation
- Rollup's bundling with Tree Shaking

and added a lot of examples with for all those features plus an example with Angular CLI if you want to use it instead of the Meteor CLI:
https://github.com/Urigo/angular-meteor/tree/master/examples

We've also updated all the latest versions including the latest Angular 5 RC and Meteor 1.6.

Please open a new issue if you encountered one.
