### ISSUE TITLE
AoT and Tree shaking for angular 4

### ISSUE THREAD

**Issue by Deadly0** [Urigo/angular-meteor#1604]
How to use AoT and tree shaking with Meteor app? Angular still have bad performance and big bundle size. AoT and tree shaking may solve that problems but i don't see any docs about this features

**Comment by blackjack0v0** [comment]
you can use ionic cli to write the app ,and use meteor as backen using https://github.com/Urigo/meteor-client-bundler ,see the tuturiol whatspp, and then 
**add** 
` import { enableProdMode } from '@angular/core';    
enableProdMode();` to your main.ts 
**run**
` ionic cordova build  android --aot  --minifyjs --minifycss --optimizejs
` 
it perform perfect on mobilephone,just 1.4mb, and load faster just need 3 sec to bootsup.

**Comment by Deadly0** [comment]
@blackjack0v0 thx, but i need build for browsers not for mobiles.

I'm personaly already migrating on React.js. Angular-meteor integration looks perspectiveless and unusable for now becouse of a lot of bugs and nobody want to fix them for more the half of year. Looks like this project is aboddoned.

**Comment by blackjack0v0** [comment]
@Deadly0  it also work for browser , you can use ngcli to build your project(don't use meteor-cli) ,just use meteor as backen . it does have many bugs, but I can't leave meteor./\.

**Comment by Urigo** [comment]
annnndddd it work!
thanks to the amazing @ardatan !

we've published new [angular-compilers package](https://github.com/Urigo/angular-meteor/tree/master/atmosphere-packages/angular-compilers) that supports all the features the Angular CLI gives you:

- Typescript compilation
- Assets compilation (HTML, styles)
- Angular's AoT compilation
- Rollup's bundling with Tree Shaking

and added a lot of examples with for all those features plus an example with Angular CLI if you want to use it instead of the Meteor CLI:
https://github.com/Urigo/angular-meteor/tree/master/examples

We've also updated all the latest versions including the latest Angular 5 RC and Meteor 1.6.

Please try it out and open a new issue if you encountered one.
