### ISSUE TITLE
Build error when building non trivial Angular 2 application

### ISSUE THREAD

**Issue by karlbanke** [Urigo/angular-meteor#1630]
I am Running Meteor 1.5.1 with Angular-Meteor. When running the build I get the following exception and the build fails. 

W20170727-17:23:43.809(2)? (STDERR) TypeError: Cannot assign to read only property 'then' of #<Promise>
W20170727-17:23:43.809(2)? (STDERR)     at patchThen (/home/banke/workspace/dpa-id/dpa-id-useradmin/src/meteor/node_modules/zone.js/dist/zone.js:942:24)
W20170727-17:23:43.810(2)? (STDERR)     at /home/banke/workspace/dpa-id/dpa-id-useradmin/src/meteor/node_modules/zone.js/dist/zone.js:968:9
W20170727-17:23:43.810(2)? (STDERR)     at Function.Zone.__load_patch (/home/banke/workspace/dpa-id/dpa-id-useradmin/src/meteor/node_modules/zone.js/dist/zone.js:85:33)
W20170727-17:23:43.811(2)? (STDERR)     at /home/banke/workspace/dpa-id/dpa-id-useradmin/src/meteor/node_modules/zone.js/dist/zone.js:645:6
W20170727-17:23:43.811(2)? (STDERR)     at performance (/home/banke/workspace/dpa-id/dpa-id-useradmin/src/meteor/node_modules/zone.js/dist/zone.js:9:65)
W20170727-17:23:43.811(2)? (STDERR)     at Object.<anonymous> (/home/banke/workspace/dpa-id/dpa-id-useradmin/src/meteor/node_modules/zone.js/dist/zone.js:12:2)
W20170727-17:23:43.812(2)? (STDERR)     at Module._compile (module.js:409:26)
W20170727-17:23:43.812(2)? (STDERR)     at Object.Module._extensions..js (module.js:416:10)
W20170727-17:23:43.813(2)? (STDERR)     at Module.load (module.js:343:32)
W20170727-17:23:43.813(2)? (STDERR)     at Function.Module._load (module.js:300:12)
=> Exited with code: 1

**Comment by Urigo** [comment]
We've done a lot of updates in the last month.

we've published new [angular-compilers package](https://github.com/Urigo/angular-meteor/tree/master/atmosphere-packages/angular-compilers) that supports all the features the Angular CLI gives you:

- Typescript compilation
- Assets compilation (HTML, styles)
- Angular's AoT compilation
- Rollup's bundling with Tree Shaking

and added a lot of examples with for all those features plus an example with Angular CLI if you want to use it instead of the Meteor CLI:
https://github.com/Urigo/angular-meteor/tree/master/examples

We've also updated all the latest versions including the latest Angular 5 RC and Meteor 1.6.

Please open a new issue if you encountered one.

We've updated the Ionic CLI tutorial and in the process of updating the Meteor CLI one.
