### ISSUE TITLE
Need to import the latest material 2

### ISSUE THREAD

**Issue by GuofuHuang** [Urigo/angular-meteor#1631]
I want to use the dataTable in the latest material 2, so I upgrade it the latest version. However, for some how the angular-meteor can't import scss file in the @angular/material/theming, it gives some errors. Does anybody already did that, if not, hope this can be done in the future.

**Comment by Urigo** [comment]
We've done a lot of updates in the last month.

we've published new [angular-compilers package](https://github.com/Urigo/angular-meteor/tree/master/atmosphere-packages/angular-compilers) that supports all the features the Angular CLI gives you:

- Typescript compilation
- Assets compilation (HTML, styles)
- Angular's AoT compilation
- Rollup's bundling with Tree Shaking

and added a lot of examples with for all those features plus an example with Angular CLI if you want to use it instead of the Meteor CLI:
https://github.com/Urigo/angular-meteor/tree/master/examples

We've also updated all the latest versions including the latest Angular 5 RC and Meteor 1.6.

Please open a new issue if you encountered one.

We've updated the Ionic CLI tutorial and in the process of updating the Meteor CLI one.
