### ISSUE TITLE
Using Angular's fakeAsync(...) in mocha tests results in an error

### ISSUE THREAD

**Issue by rgal75** [Urigo/angular-meteor#1643]
In an attempt to test some Router logic, I wanted to use `fakeAsync(...)` to verify the result of a router navigation. (I am using `RouterTestingModule` in place of `RouterModule` in the test.)

Here is the corresponding  test:

    it('navigate to "" redirects you to /home', fakeAsync(() => { 
      router.navigate(['']); 
      tick(); 
      expect(location.path()).toBe('/home'); 
    }));

As a result, I am getting the following error in the browser when running npm test:

    Error: Expected to be running in 'ProxyZone', but it was not found.proxy.js

Having searched the web for similar issues I found https://github.com/angular/angular/issues/11230 It suggests that `zone.js/mocha-patch` is already available to wrap the tests in an appropriate Zone.

If I import `mocha-patch` in `init.test.js` then I get the following error:

    TypeError: mochaOriginal.beforeEach is undefined

How can I test with `fakeAsync(...)` in a project based on `angular2-meteor-base`?

**Comment by ardatan** [comment]
This issue is probably due to version of mocha in practicalmeteor:mocha, and you have to try ardatan:mocha which has a new version of mocha that can be patched by zone.js polyfill of Angular.
You can look at the example below;
https://github.com/Urigo/angular-meteor/tree/master/tests/angular-compilers-tests
