### ISSUE TITLE
[barbatus:scss-compiler] error under Windows

### ISSUE THREAD

**Issue by atao60** [Urigo/angular-meteor#1647]
See a simplified code on Github: [meteor-angular4-scss](https://github.com/atao60/meteor-angular4-scss).
May be related to [Scss compiler error #1593](https://github.com/Urigo/angular-meteor/issues/1593)

Ubuntu 14.04.5 LTS 
Windows 8.1

Meteor 1.5.1, 1.5.2, 1.5.2.1

Doesn't use angular-meteor, but only angular2-compilers or barbatus:angular2-compilers@0.6.8 (atmosphere packages).

Everything runs fine under Linux.
But under Windows, I get:

    >meteor
    [[[[[ C:\Users\pierre\Dev\meteor-angular4-scss ]]]]]
    
    => Started proxy
    Meteor 1.5.2.2 is available. Update this project with 'meteor update'.
    => Errors prevented startup:
       
    While processing files with barbatus:angular2-compilers (for target web.browser):
    /client/stylesheets/font-awesome.scss: Scss compiler error: File to import:
    {}/node_modules/font-awesome/scss/variables not found in file:
    C:/Users/pierre/Dev/meteor-angular4-scss/{}/client/stylesheets/font-awesome.scss
    
    /client/main.scss: Scss compiler error: File to import:
    {}/node_modules/bootstrap/scss/bootstrap.scss not found
    in file: C:/Users/pierre/Dev/meteor-angular4-scss/{}/client/main.scss
    
    
    => Your application has errors. Waiting for file change.   

The issue is the same if meteor is not launched with the embedded Meteor but an external instance.

       >set MONGO_URL=mongodb://localhost:27017/db
       >meteor
 

As soon as I replace 'barbatus:angular2-compilers@0.6.8' with 'angular2-compilers', it runs fine under Windows.

Seem to be a bug. Or is there some special tricks under Windows?

**Comment by Urigo** [comment]
we've published new [angular-compilers package](https://github.com/Urigo/angular-meteor/tree/master/atmosphere-packages/angular-compilers) that supports all the features the Angular CLI gives you:

- Typescript compilation
- Assets compilation (HTML, styles)
- Angular's AoT compilation
- Rollup's bundling with Tree Shaking

and added a lot of examples with for all those features plus an example with Angular CLI if you want to use it instead of the Meteor CLI:
https://github.com/Urigo/angular-meteor/tree/master/examples

We've also updated all the latest versions including the latest Angular 5 RC and Meteor 1.6.

Please open try this out and open a new issue if you encountered one.

We've updated the Ionic CLI tutorial and in the process of updating the Meteor CLI one.
