### ISSUE TITLE
Dependencies not satisfied in tutorial

### ISSUE THREAD

**Issue by tinjaw** [Urigo/angular-meteor#1700]
RE: https://angular-meteor.com/tutorials/whatsapp2/meteor/setup

It says "Now that we have all the compilers and their dependencies ready, ", but there are still dependencies required. Here is my output at this stage"

`npm WARN @angular/compiler-cli@4.4.6 requires a peer of typescript@^2.0.2 but none was installed.
npm WARN @angular/platform-server@4.4.6 requires a peer of @angular/animations@4.4.6 but none was installed.
npm WARN @angular/tsc-wrapped@4.4.6 requires a peer of typescript@^2.1.5 but none was installed.
npm WARN tsickle@0.21.6 requires a peer of typescript@^2.1.0 but none was installed.`

**Comment by darkbasic** [comment]
These are peer dependencies, it simply means that the version currently installed is not the same version that the package expects. It should work anyway, if it doesn't work it's just because this tutorial is heavily outdated. Better follow this one: https://angular-meteor.com/tutorials/whatsapp2/ionic/setup

**Comment by tinjaw** [comment]
Thank you. That explains it.
