### ISSUE TITLE
Subscription with $rootScope.currentUser

### ISSUE THREAD

**Issue by nspangler** [Urigo/angular-meteor#181]
I am trying to subscribe to a collection using the currentUser

      $meteorSubscribe.subscribe('todos', $rootScope.currentUser).then(function () {
            $scope.todos = $meteorCollection(Todos);
        });

However when the controller first gets initialized on the load $rootScope.currentUser is undefined and the  `$meteorSubscription` does not return any values because it is passing in undefined as the Meteor.user(). However I a user is logged in it just takes a second for the app to register the logged in user. How would I achieve such functionality?

**Comment by Urigo** [comment]
This is because currentUser is also dependent on the Users collection subscription.

You can watch the $rootScope.currentUser and then when it's not undefined you can run your logic.

Might be a good idea though to change our API for that...
Any suggestions?

**Comment by revov** [comment]
Currently the solution I have found out to work best for me is as follows:
- I have a UserSession service in which I define a method that returns a promise to the currentUser.
- After that I make sure this promise is resolved before each state of routing (easy to accomplish via the *resolve* property in both the standard ngRoute and in ui-router).
- Then in the controllers I am confident that the currentUser is resolved.

The code that I currently use for the promise:
```javascript
/**
 * Returns a promise that is resolved with the currentUser - object when we have a user or null when we don't
 * @returns {Promise}
 */
this.currentUserPromise = (function() {
	var currentUserDefer;

	Tracker.autorun(function() {
		// if there is no currentUserDefer (on first autorun)
		// or it is already resolved, but the Meteor.user() is changing
		if (!currentUserDefer || Meteor.loggingIn() ) {
			currentUserDefer = $q.defer();
		}

		var currentUser = Meteor.user();

		if ( !Meteor.loggingIn() ) {
			currentUserDefer.resolve(currentUser);
		}

	});

	// return the function to be assigned as Session.currentUserPromise
	return function() {
		return currentUserDefer.promise;
	};

})();
```

**Comment by Urigo** [comment]
@revov very nice!
1. Can you share also the code that uses that (both in routes and controllers)
2. Do you think we should add that service to angular-meteor?
3. Do you think a service like that can/should be a replacement for the current user service (with $rootScope)?

**Comment by revov** [comment]
@Urigo
1. Usage in router config (for 'ui-router', but should be used the same way in 'ngRoute'):
```javascript
var currentUserResolver = [
    'UserSession',
    function(UserSession) {
        return UserSession.currentUserPromise();
    }
];
$stateProvider
    .state('home', {
        url: '/',
        templateUrl: 'client/views/home.tpl',
        controller: 'HomeController'
        resolve: {
            currentUser: currentUserResolver
        }
    })
    .state('todos', {
        url: '/todos',
        templateUrl: 'client/views/todos.tpl',
        controller: 'TodosController'
        resolve: {
            currentUser: currentUserResolver
        }
    });
```
Each time a user attempts to go to a different state a promise is obtained, resolved and attached to that state's controller scope as 'currentUser'. This solution does not aim to provide a reactive currentUser substitution to the $rootScope.currentUser (note that the currentUser in our scopes won't be reactive. It will hide the inherited currentUser property from the $rootScope. If you want the $rootScope's reactive currentUser to be inherited in your scope just resolve our promise to a different property - `resolve:{currentUserNonReactive: currentUserResolver}`).

2. I think not. A UserService would be specific for different apps. The UserService I described just wraps the functionality of my preferred Meteor login methods and returns promises.

3. The $rootScope.currentUser implementation should stay but it may be a good idea to add the 'currentUserPromise' as a separate service (and probably improve it) because this is a common problem that each angular-meteor application would face.

**Comment by Urigo** [comment]
@revov I understand.
Do you think you might want to make a pull request for currentUserPromise service?
you can start with something and we can iterate on it.  I think you are right and it is a common case.

You can also run the autorun under $rootScope like the currentUser is running (so we will still stay in Angular's scope).

**Comment by Urigo** [comment]
@revov I really want to add it but want you to start the pull request so you will get the credit you deserve..

WIll you be able to do it in the next couple days?
Thank you so much for you great help

**Comment by revov** [comment]
@Urigo, I will send you a pull request but was really busy the last couple of days and didn't want to rush it.

**Comment by Urigo** [comment]
Closed in https://github.com/revov/angular-meteor/commit/43f1c4ccbbec1e5526e40930c07584e71451d776

**Comment by nspangler** [comment]
@Urigo and @revov , I am having trouble implementing the solution. I don't understand it fully and am getting some errors. I get the `$q` is undefined and `currentUserDefer.resolve(currentUser);` throws an error. Do I need to incorporate `ngRoute` for this solution to work, i.e do I need to add `bower install angular-route@X.Y.Z` or is `ngRoute` part of this angular-meteor package?

**Comment by Urigo** [comment]
@nspangler can you share a repo?

**Comment by revov** [comment]
@nspangler If $q is undefined it means you have not injected it where you are trying to use it. Simply pass it as a parameter to your controller function (or the Service or directive where you will need it).

However you don't need to use $q to take advantage of the currentUserPromise. It is bound to the $rootScope so you have access to it in all inherited scopes (those are all scopes except directives' isolate scopes - if this is your case, just inject $rootScope service in your directive and you will have access through it).

So let's assume we are in a controller of yours and you need to do a task that depends on the currentUser:

```javascript
$scope.currentUserPromise.then( function(currentUser) {
    // Do something with the resolved value of currentUser.

    // Note that you already have it in your scope, inherited from the root scope.
    // Use '$scope.currentUser' or the 'currentUser' parameter passed to this callback

    // Once we are in this callback we know that '$scope.currentUser' is defined
    // either as the current Meteor user or as null if no user is logged in.
});
```

If you need the current user in code segments that are rerun multiple times, like watchers, event handlers, interpolated values in your markup, etc, you don't need to worry about this because when the value changes those code segments will be rerun and will acknowledge the new value. However, in code segments that are run only once (like the initialization logic in your controller) - make sure to use the resolved current user value. If you are using a routing package it can take care that this promise is resolved before it initializes your controller. But if you are not using such a package, then the above code should be used.

@nspangler You can take a look at the [documentation of $q](https://docs.angularjs.org/api/ng/service/$q) to get a deeper understanding of how promises work.

**Comment by FreedCapybara** [comment]
Sorry if here isn't the right place for this, but I'm having trouble using `currentUserPromise` with `resolve`.

According to the documentation:

$rootScope.currentUserPromise — A promise that is resolved with the currentUser when the user subscription is ready. You can wait on it in your route provider's resolve config to make sure the currentUser is not still undefined when you need it in your controllers.

The following code gives me `Error: [$injector:unpr] Unknown provider: $rootScope`:
```js
angular.module('values', ['values.controller', 'values.services'])
	.config(['$stateProvider', '$rootScope',
		function($stateProvider, $rootScope) {

			$stateProvider.state('values', {
				url: '/values',
				templateUrl: 'client/modules/values/values.ng.html',
				controller: 'valuesController',
				resolve: {
					values: ['Values', function (Values) {
						return Values.getAll();
					}],
                    loggedIn: $rootScope.currentUserPromise
				}
			});
		}
	]);
```
Is route configuration supposed to be in `module.run`?  Would you mind providing an example that shows the context in which `$rootScope.currentUserPromise` works?

**Comment by Urigo** [comment]
@FreedCapybara you need to add the $rootScope dependency to your resolve function:

                resolve: {
                    values: ['Values', function (Values) {
                        return Values.getAll();
                    }],
                    loggedIn: ['$rootScope', function ($rootScope) {
                        return $rootScope.currentUserPromise;
                    }]
                }

**Comment by FreedCapybara** [comment]
Oh, whoops.  Thanks!

**Comment by oshai** [comment]
thanks, that is very helpful (though hard to find).
in the controller itself I used `$rootScope.currentUser._id`.
Is it possible to use `loggedIn` instead? is it reflecting the user somehow?

**Comment by Urigo** [comment]
@oshai `loggedIn` is just showing if there is a login process right now

**Comment by Urigo** [comment]
@oshai where do you think we should add this to the docs?

**Comment by Tallyb** [comment]
@Urigo @oshai  it should probably be added here: http://angular-meteor.com/api/auth . 
Are you referring to "$rootScope.loggingIn" ?

adding user resolve on every state seems a bit of overhead, doesn't it? is there a problem with using the (pretty) standard solution of $on ('$stateChangeStart')?

**Comment by oshai** [comment]
Auth docs seems a good place.

**Comment by Urigo** [comment]
@Tallyb you are right
