### ISSUE TITLE
$meteorCollection.subscribe docs missing

### ISSUE THREAD

**Issue by scresawn** [Urigo/angular-meteor#183]
The [$meteorCollection API documentation] (http://angularjs.meteor.com/api/meteorCollection) has a link to documentation for .save(), .remove(), and .subscribe() methods.  The linked page doesn't have any information about the .subscribe() method. I have been trying for a long while to migrate my application from ngMeteor to angular-meteor, and the handling of Meteor collections has been especially tricky for me.

**Comment by Urigo** [comment]
@scresawn please check the fix.

Have you tried the tutorial?  I think it will help you a lot to wrap your head around the new concepts

**Comment by scresawn** [comment]
@Urigo Thanks, this helps.  I have spent a lot of time with the tutorial and watching all the YouTube videos, and they are incredibly helpful.  When using $collection before, it handled calling subscribe automatically.  Since $meteorCollection doesn't do that, I was confused about when to use $meteorCollection.subscribe() as opposed to $meteorSubscribe.subscribe().  Part of the problem was also that I was trying to pass some arguments to the publish function on the server and I had them in the wrong place.  I think I have it working now though.

Thank you very much for your help.  I'm really enjoying learning to use angular-meteor!

**Comment by aaronroberson** [comment]
Sorry to comment on a closed issue but the [http://angularjs.meteor.com/api/meteorCollection]($meteorCollection documentation) no longer exists. I thought I read in the tutorial that `$meteorCollection` is preferred over `$meteor.collection` because `$meteorCollection` will end the subscribe when the controller is destroyed. I can't find a reference to `$meteorCollection` in the tutorials though.

**Comment by aaronroberson** [comment]
Never mind I found it here http://angular-meteor.com/api/meteorCollection

**Comment by Urigo** [comment]
yes!  you can see an example here: https://github.com/Urigo/meteor-angular-socially/blob/step_12_controller_as_vm/client/parties/controllers/partiesList.ng.js

**Comment by aaronroberson** [comment]
So instead of injecting `$scope` into the controller and using `$scope.meteorCollection` like this:
```
vm.parties = $meteorCollection(Parties).subscribe('parties', {sort: vm.sort});
```
I instead have to to provide `$meteor.collection` with a closure that returns the Parties directly and then use `$meteor.subscribe` from within a `$meteor.autorun` callback like below:
```
vm.parties = $meteor.collection(function() {
    return Parties.find({}, {
      sort : $scope.getReactively('vm.sort')
    });
  });

  $meteor.autorun($scope, function() {
    $meteor.subscribe('parties', {
      limit: parseInt($scope.getReactively('vm.perPage')),
      skip: (parseInt($scope.getReactively('vm.page')) - 1) * parseInt($scope.getReactively('vm.perPage')),
      sort: $scope.getReactively('vm.sort')
    }, $scope.getReactively('vm.search')).then(function() {
      vm.partiesCount = $meteor.object(Counts ,'numberOfParties', false);
    });
  });
```
I'm feeling like these examples are not a 1:1 comparison or I have some wrong assumptions about the use of `$meteorCollection`.

**Comment by Urigo** [comment]
the subscribe is just because it is a more advanced example.

this should still work
`vm.parties = $meteorCollection(Parties.collection).subscribe('parties', {sort: vm.sort});`
