### ISSUE TITLE
HTML optimization during build process

### ISSUE THREAD

**Issue by bouchepat** [Urigo/angular-meteor#1973]
Hello, I was wondering if there is a way to optimize the HTML templates during the build process. Right now the HTML are sent as-is.

Thanks

**Comment by pmcochrane** [comment]
Is there any particular area you think you need to optimise? Compiling with aot changes the html until it is unrecognisable so I don’t know what you are targeting

**Comment by bouchepat** [comment]
Once the app is build and deployed (not in development), all the HTML templates are imported as-is, see screenshot below:

![image](https://user-images.githubusercontent.com/18633763/74461027-b766d800-4e42-11ea-98c9-fb96b88591e7.png)

This is how I build the meteor/angular app: 
 
`meteor build ../output --architecture os.linux.x86_64`

 and I deploy on a linux server.

Am I missing something?

Thanks

**Comment by pmcochrane** [comment]
I don't think you are building with AOT. Try this for your build command:

`AOT=1 meteor build ../output --architecture os.linux.x86_64`

Look in the build folder and you should not find any html files as they should all have been compiled by AOT to ngfactory.js files. They are unreadable by humans but browsers can read them much faster than having to compile angular for each component. The benefit is you angular app is much faster to load.

I'm pretty sure the compiler mentions that it does AOT stuff when it is turned on and it takes a lot longer than a normal build because of this. I can't remember as I'm using a modified version of the compiler with extra logging turned on.

**Comment by bouchepat** [comment]
Looks like it did solve my problem. Thanks a lot.

I looked again here [https://github.com/Urigo/angular-meteor/tree/master/atmosphere-packages/angular-compilers](url) and it does mention that AOT mode is enabled by default as opposed to Three-shaking mode. Anyways I'm glad it's fixed.
