### ISSUE TITLE
Authenticating event

### ISSUE THREAD

**Issue by digioak** [Urigo/angular-meteor#200]
Just finished your tutorials at https://angularjs.meteor.com/tutorial.  Very helpful!

I'm running into an issue where after I'm already logged in to Socially and I'm refreshing the page, the "Log in to create a party!" message flashes briefly before the add new party section is shown for a logged in user.  Is there a hook to render a loader?  It's not an ng-cloak issue -- precompiled markup is correctly hidden.  I know iron router has something like that but that's only for transitioning between routes?

**Comment by Urigo** [comment]
Good point.
That's because the use is in the loading state.
Take a look at the User API [here](http://angularjs.meteor.com/api/user).

Try to add 

    && !$root.loggingIn

To the condition and tell me if it works.
You can also use the promise in some way.

Tell me what worked for you, I'm just about to update the versions of the tutorial so I can add your code to it (or get a pull request from you so that you will get the credit as well)
