### ISSUE TITLE
Ability to pass arguments to meteorInclude directive

### ISSUE THREAD

**Issue by kckolz** [Urigo/angular-meteor#261]
The meteorInclude directive only checks for a template name. In some cases Blaze allows for options such as {{> loginButtons align="right"}} which would be nice to be able to do with the directive. 

As it stands I am not sure how to recreate this behavior.

**Comment by Urigo** [comment]
Yes you are right, we have that task on our roadmap - https://trello.com/c/vdfMoTQw/25-add-atributes-support-to-meteor-include

It is not high priority since you can still do that today by creating template that includes {{> quickForm collection="Books" id="insertBookForm" type="insert"}} and include that template with meteor-include...

Closing as there is a solution and also a feature on the roadmap.
That said, we would love a pull request for it!
