### ISSUE TITLE
Question: Getting AngularMeteorObject without knowing the _id?

### ISSUE THREAD

**Issue by maersu** [Urigo/angular-meteor#273]
Great Package! Thanks a lot!
(Sorry, this is maybe not the right place to ask questions...)

How can i get a AngularMeteorObject without knowing the *_id*

Something like:

```
$meteor.object(Collection, {userId: Meteor.userId()})
```

Thanks

**Comment by CharlSparksNZ** [comment]
@maersu Well since your example uses a user I will go with that. You can use $rootScope.currentUser._id if you have a user authenticated. The $rootScope will always contain a user if one is logged in. If this is the case you might need to ensure a user is authenticated when visiting this page, so check out step 8 of the tutorial for a simple example of making sure users are authenticated before rendering the route. 

Or alternatively you can use $meteor.requireUser().then() as well to wrap your logic in a promise to ensure a user is present if this is being done from a controller or factory. Best of luck!

**Comment by maersu** [comment]
@CharlSparksNZ thanks for your answer!

I was not precise enough. I was wondering how I can get the AngularMeteorObject without knowing the object._id

The Problem is that $meteor.object does not accept a filter object (like findOne) only the id of the object.
My actual workaround is something like that:

```
_object = Collection.findOne({field: query})
# getting the _id of the object to get the $meteor.object
$scope.myObject = $meteor.object(Collection, _object._id)
```

I was wondering how to make this in one step

**Comment by netanelgilad** [comment]
@maersu Actually, $meteorObject calls the second parameter id, but the object is used like any other selector object and is passes to a findOne function afterwards.
So you could try just using `$meteor.object(Collection, selector)` and see it that works for you.

**Comment by Urigo** [comment]
@netanelgilad nice answer
@CharlSparksNZ also thank you so much
@maersu closing, please re-open in case a problem pops up

**Comment by maersu** [comment]
Thanks a lot for your help guys!

@Urigo thats maybe something you could mention in the docs:
http://angularjs.meteor.com/api/meteorObject

**Comment by Urigo** [comment]
@maersu yes that's a good idea, do you want to pull request the docs and add an example that makes it more obvious?
https://github.com/Urigo/angular-meteor/blob/master/.docs/angular-meteor/client/views/api/api.meteorObject.html

**Comment by maersu** [comment]
@Urigo i will do that next week, thanks!

**Comment by maersu** [comment]
@Urigo sorry, I was to lazy and to late, you already did it :)

**Comment by Urigo** [comment]
;)  thanks for bringing that up
