### ISSUE TITLE
Arrays hashkeys?

### ISSUE THREAD

**Issue by berkaey** [Urigo/angular-meteor#299]
I think I found a bug and a solution. if the object has an array it will give this error 
```
Exception while invoking method '/contents/insert' Error: key $$hashKey must not start with '$'
```
solution
```
# cleanup hashkeys
item = angular.copy(scope.content)
angular.forEach item.images, (image) ->
 delete image.$$hashKey
$rootScope.contents.save(item)
```

**Comment by Urigo** [comment]
@berkaey yes you are right, we had that code and removed it because of efficiency (and because we forgot about the $$hashkey...)

I've added it here:
https://github.com/Urigo/angular-meteor/commit/86cde85f30f9033ce51d29ba85acac6f3d93c015

We don't need to do 'foreach' and remove the $$hashkey because angualr.copy does that for us.
But, the AngularMeteorCollection.save function has to be very efficient and angular.copy is a little expensive.
the reason we have to do angular.copy is that otherwise we are keeping the reference and angular bring back the $$haskey even before we save it...

1. We know we don't need to check for $$hashkey if the save came from the autobind as $watch remove that from the results, so I've added a flag to the end of the parameters
2. Checking if we need to do angular.copy by running over all the nested object looks to me exactly as efficient as doing angular.copy (the only difference is the copying action which is not expensive).

What do you think about it @netanelgilad @barbatus ?
do you have any suggestions how to make it more efficient?

**Comment by barbatus** [comment]
First of all angular.copy is a deep copy which means it might be really slow.
Secondly, Angular seems to add $$hashkey when an array is used in ng-repeat only which means it's not all the time. As a result, I'd suggest to leave it as a responsibility of user to clean an object before saving.

**Comment by barbatus** [comment]
As a second I thought, I had potentially even more useful idea: since in most cases objects to save will have simple structure, it makes sense to check and clean only two first levels (object itself and objects in any subarray) and only otherwise throw an exception on the collection.insert if it's somewhere deeper.

**Comment by auterium** [comment]
I came across this issue myself and the problem is bigger when you are using autosave: you cannot clean the $$hashKey manually. As a quick fix I looked for the $$hashKey on the setDiff and just deleted it, but I don't think is the best approach to it.

I like @Urigo approach, but I'm also concerned abut the performance, though for my case it wouldn't be a big deal as the objects & collection are very small.

I did some tests and Angular adds the $$hashKey to the root of the object and not the inner objects, though I still think that in some cases the inner objects can get such key.

How about this: AngularMeteorCollection.save()'s 3rd param (hashKeysMightExist) is a multi-value param:
- true (default): removes the $$hashKey from the root only using a simple delete item.$$hashKey
- "recursive": uses angular.copy()
- function(item): have a custom function that will be the one that eliminates any undesired keys
- false: do nothing

**Comment by barbatus** [comment]
@auterium If it's explicit save -- it's ok but what about autosave. How do you suppose to pass all that params to autosave? Also, how that function (3d in the list) is supposed to be used? Should it be called on failure and then collection insert will restart or before calling insert? I guess the latter - then it's the same as cleaning it before passing to save, isn't it.

**Comment by auterium** [comment]
@barbatus sorry I didn't explained myself correctly.

I forgot to mention that those options should be passed to the $meteor.collection() or $meteor.object() methods, so when autosave is invoked, it's done so with such options.

The idea behind the cleaning function is to be used with the autosave.

**Comment by netanelgilad** [comment]
Just a small issue. @Urigo if you remember we didn't remove the `angular.copy` because of performance (though it was also considered). We removed it because it caused problems with CollectionFS object. If you try to save a File object (like CollectionFS does) then `angular.copy` causes problems when copying a File object.
So anyway, `angular.copy` should be avoided for those situations..
