### ISSUE TITLE
http://angular-meteor.com/tutorial/step_12 "Stopping a subscription"

### ISSUE THREAD

**Issue by pdavidow** [Urigo/angular-meteor#417]
... is missing the code for "subscriptionHandle".

Also, in general this tutorial is full of typos and broken sentences -- which only adds to the complexity.

**Comment by Urigo** [comment]
@pdavidow thanks for your feedback, there is no need for subscriptionHandle as the $scope.$meteorSubscribe closes it when scope destroys automatically like described in the tutorial, but you are right and I've added an explanation about how the manually stop it just in case with reference to the API docs:
https://github.com/Urigo/angular-meteor/commit/e0850051e9a2b4e0c344d553a5df7280a45dcda3

As for typos and broken sentences, I'm sorry but U;m not a native speaker and I try my best.
I've added a button on each page "improve this doc" so that people can help me and correct stuff.

Thanks again
Uri

**Comment by pdavidow** [comment]
I was just going by the Code Diff (button at bottom of http://angular-meteor.com/tutorial/step_12) which shows (for the first time):

$scope.$on('$destroy', function() {
      subscriptionHandle.stop();
});

**Comment by Urigo** [comment]
ohh I understand.
Yes the sources needs to be updated.
Will do that very soon
