### ISSUE TITLE
IronRouter seems not to work

### ISSUE THREAD

**Issue by Nomeasmo** [Urigo/angular-meteor#48]
Although stated in the docs in my system an angular control does not work via the `{{< yield}}`.

It works if I refer the template from within the body directly.

Is there anything else needed (ònBeforeAction`) or similar?

**Comment by mmuenster** [comment]
I am having this same problem that the meteor pad referenced above generates but the solution above throws an error.

angular.element(document).injector() is undefined so the 'invoke' method throws an error.

I am running the above code in a Meteor.isClient section.  

Any help would be appreciated.

**Comment by martinoosthuizen** [comment]
Hi @mmuenster. You're probably not working on this issue any more, but for anyone else, I'm pretty sure the source of your problem is the scope of your angular app. For example if your ng-app is defined on the <body> tag, the injector on the document element will be undefined. You can use a selector like $('body') for example to get a handle on the injector within the scope of your angular app. Hope that makes sense.
