### ISSUE TITLE
How do I know if $scope.$meteorObject(id) found an object or not?

### ISSUE THREAD

**Issue by pgrm** [Urigo/angular-meteor#484]
Hi, great framework, which I still need to wrap my head around a bit.

I have a `ListController` and an `ItemController`. The `ItemController` is in a nested state of the `ListController` it loads the item details and by doing this, it also checks if the item actually exists. If the item doesn't exist, the `ItemController` redirects back to the root state.

This is what I have so far:

    this.current = $scope.$meteorObject(Items, $state.params['itemId']);
    if (!this.current._id) { 
        $state.go('^'); 
    } else { 
        /* initialize everything */ 
    }

If I type in a wrong id on purpose it works. If I type in the correct id, it also works. But if refresh the browser, `this.current._id` is undefined even though, the id was correct.

I've tried using `$scope.subscribe` but the promise was never called. My `ItemsController` contains the is running subscribe on the `Items` collection:

	this.items = $scope.$meteorCollection(Items);
	this.items.subscribe('items');

I thought $meteorObject would be synchronous but I guess there are some exceptions to it? Or is my code completely wrong?

**Comment by ccortezia** [comment]
Ok, I guess you already got how meteor subscriptions work, right ? Anyway, remember: data should be available at the client some time after the respective subscription enter its ready state. 

If you happen to call $meteorObject or $meteorCollection at this moment (after the data has already arrived from a subscription), it will seem to be a synchronous call, since the available data will be promptly bound to the return value. But if you call these functions before the data from the subscription has arrived, the variable bound to their return values should hold empty collections until some data really arrive at the client. 

One way to perform side-effects over delayed data is to watch for these bound variables at the controller level. 

One way to make sure a local collection is totally synced with a remote collection is to rely on a published count of total elements (see [percolatestudio:publish-counts](https://github.com/percolatestudio/publish-counts)), and unfortunately, watch for its changes too. This technique happens to be pretty effective if you want to perform client side joins too, and require several collections to be fully available before doing anything useful.

Regarding your question on how to make sure an object exist and perform a potential state change, one "promise way" to do this would be to have a server side check method, and then call it with $meteor.call from a route resolve function or from your controller body, or from wherever.

PS: I think the proper place to ask these sort of questions would be stack overflow.

**Comment by pgrm** [comment]
Ok thx, and there isn't any property on the object which would be indicating if it was already loaded or still not? (I couldn't find any)

If I write a server method to do this, and the method is defined in the lib folder for instance (accessible by server and client) will I still get meteor's latency compensation, in case the collection is already available offline? - I read, this to be true if you want to perform changes on the database and the meteor method would throw an error. In that case, meteor wouldn't send it to the server and directly deal with the error thrown by the client. But I'm not sure how it works with retrieving data.

PS - yes you're right SO might seem like a better fit, however I've found, that generally answers in github issues tend to be more detailed and I really thought, there should be a way to distinguish between waiting for the object and not getting any object. It might be that this is very difficult, or not possible, due to features of meteor, but I hope you agree that your very helpful suggestions still sound more like a workaround than the actual solution.

**Comment by ccortezia** [comment]
> any property on the object which would be indicating if it was already loaded or still not?

I don't think so. And considering the way meteor work, adding it to angular-meteor may not be really simple. @Urigo probably has a better call on this, perhaps an existing solution I am not aware of ? 

And yes, I aggre my suggestions seem a bit hacky, and I myself avoided them for as long as I could until I found no other way to assert client-side collections are fully loaded (reactively). But the final coded result is not complex at all, and I suggest you try it yourself.

**Comment by Urigo** [comment]
@pgrm $meteor.object binds to Meteor Collection.
Meteor Collection is empty until a subscription has been called and complete.

So like @ccortezia said, binding to $meteor.object is ok and correct and not related to subscriptions.

As for your question, you need to make sure you call your `if` statement only after the subscription finished it's initial loading.

`$meteor.subscribe` returns a promise that is called when the subscription is ready, so, you have 2 options to use that:

* Using the promise inside the controller:

```
     this.current = $scope.$meteorObject(Items, $state.params['itemId']);

     $meteor.subscribe('items').then(function(){
       if (!this.current._id) { 
           $state.go('^'); 
       } else { 
           /* initialize everything */ 
       }
     })
```

* Use ui-router resolve function to enter the controller only after the subscription has ended:
```
    .state('partyDetails', {
      url: '/parties/:partyId',
      templateUrl: 'client/parties/views/party-details.ng.html',
      controller: 'PartyDetailsCtrl',
      resolve: {
        "data": ["$meteor", function($meteor){
          return $meteor.subscribe('items');
        }]
      }
    });
```

**Comment by Tallyb** [comment]
oh, how we need best practices / style guide document...

**Comment by pgrm** [comment]
I guess, it would be great, if this example could be added to the party
tutorial.

Thx for the help

**Comment by Urigo** [comment]
That's a great idea!
How are where will you add it?

**Comment by pgrm** [comment]
@Urigo your suggested solution with `$meteor.subscribe` in resolve would need me to stop the subscription, when the controller (scope) is being destroyed, otherwise I'd end up with memory leaks, is that correct?

In that case there wouldn't be too much difference between running `$scope.meteorSubscribe` and handle the rest of the initialisation inside the promise callback, or making sure the controller listens to `$destroy` on it's scope to stop the handle.

**Comment by Urigo** [comment]
yes you are right. 
You don't have `$scope` in resolve so it's better to do it inside the controller like in the first example but with $scope.$meteorSubscribe
