### ISSUE TITLE
Iron Router / Flow Layout - compile Angular after waitOn and subscription resolve

### ISSUE THREAD

**Issue by Siyfion** [Urigo/angular-meteor#493]
So for example, when using `ng-include` nothing appears at all, I'm sure it's something stupid, but I can't see it for love, nor money. Here's my files:

`client/templates/main.html`
``` html
<head>
  <title>LabelLogic Live</title>
  <meta name="description" content="Planglow's next generation labelling system">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <link rel="icon" sizes="16x16 32x32" href="/favicon.ico">
</head>

<body ng-app="LabelLogicLive"></body>
```

`client/lib/angular-init.js`
``` javascript
// This code only runs on the client
angular.module("LabelLogicLive", ['angular-meteor']);
```

`client/templates/field_editors/recipe_editor/recipe_editor.html`
``` html
<template name="recipeEditor">
  <p>This render's just fine...</p>
  <ng-include src="'client/templates/field_editors/recipe_editor/recipe-grid.ng.html'"></ng-include>
</template>
```

`client/templates/field_editors/recipe_editor/recipe-grid.ng.html`
``` html
<p>Nothing here {{ 'yet' + '!' }}</p>
```

Obviously there's also some code that includes the `{{> recipeEditor}}`, but as the code states, the `<p>` is rendered fine.

**Comment by Tallyb** [comment]
You are using an ng-include within a blaze template? Is this supported? ( I know blaze within angular is, not sure about the other way around...)

**Comment by Siyfion** [comment]
@Tallyb Well the tutorial shows a `*.html` file using `<ng-include>` so I assumed that it's being parsed by the same Blaze renderer, and as such is fine...?

**Comment by Siyfion** [comment]
@Tallyb However you're indeed correct, if I take the line out of the template, and move it into `main.html` like so:

```html
<head>
  <title>LabelLogic Live</title>
  <meta name="description" content="Planglow's next generation labelling system">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <link rel="icon" sizes="16x16 32x32" href="/favicon.ico">
</head>

<body ng-app="LabelLogicLive">
  <ng-include src="'client/templates/field_editors/recipe_editor/recipe-grid.ng.html'"></ng-include>
</body>
```

**Comment by Siyfion** [comment]
Surely if this isn't possible, it means that unlike React, it's almost impossible to slow-transition across to Angular, from an existing Blaze application?

**Comment by Tallyb** [comment]
I am not familiar with the blaze react option. With angular you will probably have to do it "outside-in", namely - have the wrapper being angular (probably using ui-router) and use blaze templates where needed using meteor-include directive.
Also, coming from Angular, I cannot see a good reason to wrap Angualr with Blaze, as Angular is a much more advanced front end framework. 
Maybe people here have other suggestions for the transition.

PS I am a woman - aren't we always right?  ;)

**Comment by Siyfion** [comment]
@Tallyb Regardless of which front-end framework is more powerful (that will be debated until the end of time), if you've got an existing application written in Blaze and want to switch or make use of some angular features, then you need to be able to be able to wrap angular in blaze...

Any thoughts @Urigo ?

**Comment by Urigo** [comment]
@Siyfion can you send an example repo?
I will have a look on it and see why it's not rendering and if that's possible

**Comment by Siyfion** [comment]
I stand corrected @Urigo, I've just tried creating an example, and it works, so it's clearly me doing something wrong... What, I have no idea!

This does work however:

```html
<head>
  <title>angular-meteor-example</title>
</head>

<body ng-app="TestApp">
  <h1>Welcome to Meteor!</h1>
  <!-- ng-include outside of a Blaze template -->
  <ng-include src="'test.ng.html'"></ng-include>
  {{> hello}}
</body>

<template name="hello">
  <p>This text will be rendered.</p>
  {{> secondLevel}}
</template>

<template name="secondLevel">
  <!-- ng-include inside of a Blaxe template -->
  <ng-include src="'test.ng.html'"></ng-include>
</template>

```

**Comment by Siyfion** [comment]
@Urigo Oh my god, that took some finding, but I've finally figured out the root cause of the issue...

Here's a repo that highlights the issue: https://github.com/Siyfion/angular-meteor-example

Essentially, everything works fine, unless you use `iron:router` (which most Blaze apps do!), at which point, if the route has ***any*** `waitOn` configured, it breaks all of the angular integration. If you comment out this: https://github.com/Siyfion/angular-meteor-example/blob/master/lib/router.js#L4 onwards, you'll see that it starts working again.

Perhaps @tmeasday, @dandv, or others from the `iron-router` project need to be involved in this discussion, as the issue probably lies in IR, rather than this package.

**Comment by dandv** [comment]
Hi @Siyfion, I'm not really involved in `iron-router` actually. Hope Tom can pitch in, now that [he's with MDG](http://info.meteor.com/blog/welcoming-percolate-studio-to-meteor-development-group).

**Comment by Siyfion** [comment]
Ah sorry @dandv, I just saw that you were pretty much the second highest contributor to `iron-router` albeit a fair way behind @tmeasday! :+1:

**Comment by tmeasday** [comment]
OK, github is doing something weird on that contributors graph, @cmather is the person you want to talk to ;)

But I think I can diagnose this one:

If you use `waitOn`, IR will render a (blaze) loading template into the layout while waiting on data. I'm not sure how the angular/IR integration is supposed to work, but I'd simply replace `waitOn` with `subscriptions` -- it does the same thing without doing any loading business.

**Comment by Siyfion** [comment]
It's perhaps also worth mentioning that @arunoda's Flow Router / Flow Layout also suffer from a similar issue; if you change the `router.js` code in the example repo to the following:

```javascript
FlowRouter.route('/', {
  name: 'dashboard',
  subscriptions: function (params, queryParams) {
    this.register('testSubscription', Meteor.subscribe("thisBreaksThings"));
  },
  action: function () {
    FlowLayout.render('dashboard');
  }
});
```

Although it fails to work in this instance, regardless of whether the subscriptions are used or not.

**Comment by Siyfion** [comment]
I'm pretty certain it's due to the way it's being hooked into Iron Router in `angular-meteor.js` here: https://github.com/Urigo/angular-meteor/blob/master/angular-meteor.js#L17-L31

As @tmeasday has suggested, IR renders a loading template when using `waitOn`, which I think triggers this code to run, but with the "loading" template rather than the actual finished template... And it seems as though it simply doesn't have any support at all for Flow Layout/Router; perhaps @arunoda might be able to suggest a "best-strategy" for adding support for that?

**Comment by arunoda** [comment]
@Siyfion frankly I'm quite not sure what's going on here other than ng-meteor hardcoded IR :)

**Comment by Siyfion** [comment]
@arunoda Is there any sort of "hook" in Flow Layout that @Urigo could use to detect when the render is complete, as it looks as though he then needs to run it through an Angular `$compile` operation to get the angular-ness.

**Comment by arunoda** [comment]
Ah okay. Got it.
This is something we are doing for the first-time or for every route change.
BTW: I hope there is a built in router for angular? isn't it? This is related to flow-layout. But..

**Comment by Siyfion** [comment]
There is an official Angular Router (https://atmospherejs.com/angularui/angular-ui-router) but obviously you can't use that if you want a mix of Blaze and Angular... Which I admit is clunky, but it'll help people transition from one to the other without a complete re-write.
What I was hoping to do was to use Angular to render an `ng-grid` with some data, as there isn't a grid for Meteor/React that comes close to it's functionality.

**Comment by arunoda** [comment]
We don't have a such a hook. Things get little tricky when booting up the app since we use both `Meteor.startup` and `Meteor.defer`. 

Anyway, if someone can just tell me the exact requirement, I can work out a new API for you guys :)

**Comment by Siyfion** [comment]
Well I'm just the guy that pointed out the problem, @Urigo is the one who'll be able to tell you what he ideally needs, but awesome that you're open to adding some API calls to help! :+1:

**Comment by Urigo** [comment]
@Siyfion Sorry for the late response and greetings from Switzerland where I'm traveling now ;)

First thing - I think like @arunoda mentioned, this is an old code that hard codes IR.
I think this kind of code better belongs to a separate `iron-router-angular` package.
Same for `flow-router-angular`  (or some other name...)

Then it will also be much easier to understand when did the layout finished loading (by each router's logic) and and `$compile` that particular layout against scope. 

@Siyfion do you want to try hacking on this?  I can certainly help, but would love someone from the Blaze routers area to hack with me on it.

I also wonder what does @barbatus has to say about that

**Comment by barbatus** [comment]
@Siyfion @Urigo 
I had similar issue long time ago, see [154](https://github.com/Urigo/angular-meteor/issues/154).
The reason is If you use ````waitOns```` IronRouter will substitute a router template with a loading one and, in case of meteor-angular, will never get back without special handling. I eventually came up with this solution https://github.com/Urigo/angular-meteor/commit/69b79878cc7e9239980cb2525afaa0364157a431, it worked but it looked messy to me, so  I ultimately removed it and continued with, like was mentioned here, ````subscriptions```` instead of ````waitOn```` and FastRender.

**Comment by Siyfion** [comment]
@Urigo So just to make sure I have the correct idea, we need to force a `$compile` after every layout/route change correct?

If this is the case, for the routers:

- *Flow Layout* -  @arunoda would need to add an API call to Flow Layout to detect when a render operation has been performed. Then we can hook into that and call `$compile`.
- *Iron Router* - Hopefully @cmather might be able to suggest a way to hook into Iron Router that is 100% reliable and also gets around the `waitOn` issue. Allowing for Angular code in both the loading template and the final template.

**Comment by barbatus** [comment]
@Siyfion 
Yes, you almost got it right.
If you remove appLoaded [here](https://github.com/Urigo/angular-meteor/blob/master/angular-meteor.js#L23) you will get ````onAfterAction```` running right after each route change, sometimes though it runs twice. This happens (````onAfterAction```` executed twice) is when you are making of ````waitOn```` (but looks like not only in this case); route doesn’t change but layout does though IronRouter doest make difference and runs ````onAfterAction```` one more time with ````Router.current().ready() == false````.

So you need to check this situation or otherwise you will get ````$compile```` it twice as well.
You can look at this [fix](https://github.com/gmr2/GimmeRide/blob/master/client/ng/routes.js) which is a refined version of what was mentioned above. This is what I use in my project and works pretty good to me. I was a bit wrong above mentioning ````subscriptions ````. I got rid of that at some point too.

**Comment by Siyfion** [comment]
@barbatus Thanks! So you're saying that `onAfterAction` runs twice when `waitOn` is used? Isn't that expected, as it'll fire once for the "loading" template and then again once the waitOn's are complete and it's rendered the main template?

**Comment by Siyfion** [comment]
Having said all this, wouldn't it be simpler just to add some kind of hook into `Blaze.render` & `Blaze.renderWithData`, that way it also accounts for any user-rendered templates (think modal windows, etc.)

**Comment by barbatus** [comment]
@Siyfion 
Well, I didn't say it wrong; it depends how ````onAfterAction```` is defined. Nowadays it runs at route changes, as well as at layout changes of the same route.

On the second, yes, I think it needs improvements. For example, there is no template rendering completion event (at least I didn't find) to hook up to. So be careful of mixing Blaze templates and Angular, i.e. try to use Angular at first level templates, max - second level, since ````Tracker.afterFlush```` doesn't say anything about rendering.

**Comment by Siyfion** [comment]
So @arunoda if we could have an API call for an event that gets fired after **every** layout change I think that would make the Flow integration nice and easy... IR seems a bit more messy.. :/

**Comment by arunoda** [comment]
@Siyfion I think that's possible. I can fire it just after we send the request to Blaze. You may need to call `$compile`(or similar) in `Tracker.afterFlush()` since that's when the rendering gets completed.

But it's depend. I'll make the API.

**Comment by Siyfion** [comment]
Great, thanks @arunoda!

**Comment by dhobla007** [comment]
@Siyfion i am also facing same issue but not in first call of router but instead in second call of router.
ex.
Call 1-- 
Router.route('/', {
  name: 'Login'
  });

call 2--
Router.route('/Dashboard', {
  name: 'Dashboard'
  });

Dashboard template calls another template which is having ng-include and not getting loaded.

if i make Dashbaord as first call then it is loading perfectly.

Please let me know  what might be cause for this.

**Comment by rossmartin** [comment]
@Siyfion @Urigo @arunoda 

Thanks for all the info on this issue everyone.  I work on a project that is fairly invested in iron router and blaze but I prefer to work with angular so that partially explains why I'm commenting here.  I spent a few hours trying to get angular ui-router to co-exist with iron router and I had no luck (I read your answer to this stackoverflow post [here](http://stackoverflow.com/a/31118153/1673842) @Urigo but that wasn't working for me, neither was the accepted answer there).

I want to share the approach I use for `$compile`ing an angular template for a particular route in iron router.  Thankfully I don't use `waitOn` or `subscription` except for one route so this approach below works well.  Anyone else in my situation can probably make use of this solution.

Example of a route that `$compile`s a template from the `$templateCache`.
```javascript
Router.route('/ng/test', function() {
  this.layout('mainLayout');
  let bodyEle = angular.element(document.body);

  bodyEle.injector().invoke(['$rootScope', '$templateCache', '$compile', '$timeout',
   ($rootScope, $templateCache, $compile, $timeout) => {
    let template = $templateCache.get('client/Test.ng.html');
    let compiled = $compile(template)($rootScope);
    $timeout(() => {
      $('#angular-view').append(compiled);
    });
  }]);
});
```

I empty the container for my angular views in `Router.onBeforeAction`.  I have this `#angular-view` element below the `{{> yield}}` region on the `mainLayout` blaze template.
```javascript
Router.onBeforeAction(function() {
  $('#angular-view').empty();
  // ... removed code for brevity
  this.next();
});
```

`client/Test.ng.html`
```html
<div ng-controller="TestCtrl">
  <p>Nothing here {{ 'yet' + '!' }}</p>

  {{foo}}

  <button type="button" class="btn btn-default" ng-click="onClick($event)">Click Me</button>
</div>
```

`client/Test.ng.js`
```javascript
angular.module('my-app').controller('TestCtrl', ($scope) => {
  Meteor.startup(() => {
    console.log('TestCtrl');

    $scope.foo = 'bar';

    $scope.onClick = (e) => {
      console.log('onClick');
    };
  });
});
```

I'm using the below packages that allow this setup to work.  I think `ng-annotate` is working correctly for `.ng.js` files.
```
angular-with-blaze
blaze-html-templates
urigo:angular-blaze-template
```

Hopefully this helps someone.  I feel much better being able to use angular now in this project especially since I don't have time to port lots of existing blaze code to angular.  If anyone knows of a better way for anything above please let me know :beers:

**Comment by Urigo** [comment]
@rossmartin thank you for this great answer!
If you think we should elaborate more somewhere in the doc about that solution feel free to PR the docs.
