### ISSUE TITLE
Console error: WebSocket is already in CLOSING or CLOSED state.

### ISSUE THREAD

**Issue by JohnAReid** [Urigo/angular-meteor#497]
I found out I am not alone (http://stackoverflow.com/questions/30900649/meteor-websocket-is-already-in-closing-or-closed-state) in getting this error message in the console window. 

Is it a real error message? as I just hate to see error messages in the console window!

**Comment by dotansimha** [comment]
Hi @JohnAReid ,
I don't think that this is an issue with angular-meteor, but with Meteor itself.
Also, this might caused by a breakpoint that pauses your browser and the WebSocket gets a timeout, or, sometimes when changing many files in a short time - the browser refreshes multiple times and causes that error.

**Comment by JohnAReid** [comment]
@dotansimha 
Thanks you right it does happen when I have breakpoint.

**Comment by shubhankarGoku** [comment]
WebSocket is already in CLOSING or CLOSED state.
(anonymous) | @ | browser-sync-client.js?v=2.18.13:3
-- | -- | --

**Comment by FelipeAragao** [comment]
Please help
