### ISSUE TITLE
limit the initial collection, but allow the local collection to grow.

### ISSUE THREAD

**Issue by tgienger** [Urigo/angular-meteor#537]
I'm sure this is more of a meteor question rather than angular-meteor specific, but since I'm using angular-meteor ...

Is there a way to set a limit of say 25 for a collection, but then have the client side collection grow when a new one is added rather than getting the latest 25 again?

For instance, get the last 25 comments from the server. When a new comment is added send that one new (or however many) comment to the clients w/o resending the latest 25 again.

**Comment by ccortezia** [comment]
Have you tried to use two different publications ?

1. publication 1 would provide the initial 25, and would not provide any more data after data. If you dont' know how to limit records on a cursor you can read about it on mongo and meteor docs.
2. publication 2 would provide the latest comments, and would cause the client collection to grow.

Since meteor collections automatically merge data from different subscriptions, you would end up with a single collection that could be queried regardless of the publications that provided the data.

**Comment by Urigo** [comment]
@tgienger what you described is how it is supposed to work.
Can you please provide an example where it isn't the case?

**Comment by tgienger** [comment]
@Urigo If you set a limit of 25, the local collection will always be 25. What I was wanting was to be able to grab the latest 25 out of the collection and then allow the local collection to grow beyond that. I can't recall what I ended up doing, but basically what @ccortezia mentioned works. Grab a subscription that gives you the latest 25, then stop it so it no longer updates, then have another subscription that only gets newly added items.

**Comment by Urigo** [comment]
With the new [Angular Meteor 1.3 release](http://info.meteor.com/blog/angular-meteor-1.3) we are using the regular Meteor API so that question becomes a regular Meteor question and should be posted on the [Meteor forums](forums.meteor.com) or Meteor issues
