### ISSUE TITLE
Server side paging + CSV file

### ISSUE THREAD

**Issue by sali1982** [Urigo/angular-meteor#580]
Thanks for your great tutorial about making tables and so on.

I added a CSV functionality to convert the whole data to CSV. 
As you know, we have subscribe on server to only give us 10 records, I need to get the whole data for the CSV file. 

What approach you would take to do this? 
What I did was adding another subscribe, which gives all the data, but in this case the pagination won't work, as it stucks on my second subscribe.

Thanks for the reply.

SA

**Comment by Urigo** [comment]
Hi @sali1982 
Yes that's the answer - creating another subscription for the CSV file.

But in order to keep your pagination working, you have to close this subscription right after.
You can read more about that in the tutorial section that talk about stopping the subscription:
http://angular-meteor.com/tutorials/angular1/search-sort-pagination-and-reactive-vars#stoppingasubscription

There is also another way which is very interesting.
It is described very nicely in this article: https://www.discovermeteor.com/blog/pagination-problems-meteor/

To make things short - you can use this package: https://github.com/percolatestudio/find-from-publication/
to separate data between different subscriptions, even if they are with the same data.

Good luck and let me know how it worked for you!

**Comment by sali1982** [comment]
But in the first link it has this line:
$scope.party = $meteor.object(Parties, $stateParams.partyId);
Which is to close subscription. 
Please note that in my case I do have only one controller. my table and CSV are in the same controller. 
Can I still do close it somehow? 

then in my case which I have only one controller, should I do this:

subscribe to the csv_one
then generate the csv,
right after subscribe to the non_scv_one by this line:  $scope.$meteorSubscribe(' non_scv_one');

If that is what you mean, I already did, and nothing happened. I will try your other method though and will update here!

**Comment by Urigo** [comment]
It closes the subscription but when the controller closes.
If you want to close it before you need to get the subscription handle and call the stop function.

You can look at the example here: http://angular-meteor.com/api/subscribe
