### ISSUE TITLE
ui-bootstrap dropdowns

### ISSUE THREAD

**Issue by ilantoren** [Urigo/angular-meteor#593]
I'm trying to migrate a project using angular to angular-meteor and I see that my dropdown buttons are no longer functional (i.e.  click but no drop down, content stays hidden).  I assume that the libraries are the issue.  The libraries in https://github.com/Urigo/angular-meteor/issues/496 are not sufficient, Are there any working examples?

Here is my non-working example  https://github.com/ilantoren/ui-angular-meteor-bug

**Comment by Urigo** [comment]
Why are you adding bootstrap with bower and not from Atmosphere?

**Comment by ilantoren** [comment]
I don't see that I used bower.  I took an early stage of the tutorial and pasted in a drop-down button menu as  done in the ui-angular page.

**Comment by dotansimha** [comment]
@ilantoren  @Urigo 
Hi
First, why do you use both `bootstrap3-less` and `twbs:bootstrap` ? you should use one of them, otherwise it loads the Bootstrap library twice! 
I just removed `bootstrap3-less` from you project, and used the original Bootstrap dropdown example from it's docs:
```html
<div class="btn-group">
  <button type="button" class="btn btn-default dropdown-toggle" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
    Action <span class="caret"></span>
  </button>
  <ul class="dropdown-menu">
    <li><a href="#">Action</a></li>
    <li><a href="#">Another action</a></li>
    <li><a href="#">Something else here</a></li>
    <li role="separator" class="divider"></li>
    <li><a href="#">Separated link</a></li>
  </ul>
</div>
```

And it works great:
<img width="254" alt="screen shot 2015-10-18 at 22 30 55" src="https://github-cloud.s3.amazonaws.com/assets/3680083/10566164/ea88acb4-75e7-11e5-9b61-b82695fff72b.png">

So I do not think it has any thing to do with angular-meteor...
Please verify it in your code.

**Comment by Urigo** [comment]
Thanks @dotansimha
