### ISSUE TITLE
Angular Animate (ngAnimate) not working with angular-meteor-1.0.0-rc5

### ISSUE THREAD

**Issue by zakmandhro** [Urigo/angular-meteor#662]
It looks like Angular Animate (official v1.4.5) is not working when loaded in the context of angular-meteor. The [basic animate example from Angular docs](https://docs.angularjs.org/api/ng/directive/ngSwitch#animations) is failing with no error but no animation either.

Here's a plain [Meteor project repo](https://github.com/zakmandhro/meteor-angular-animate) to reproduce it.

Did I miss something?

**Comment by mackbrowne** [comment]
@zakmandhro just tried your example and can confirm the issue.  Am able to reproduce it... couldn't figure out what was wrong.

**Comment by zakmandhro** [comment]
@Urigo not sure what's going on but we should probably check this before bumping to 1.0 final, in case the root issue has implications on other JS libraries.

**Comment by DAB0mB** [comment]
Ok, it took me some time but i finally figured it out. The short answer is **no**, there's nothing wrong with angular-meteor. Here's a little break down. angular-animate will only animate elements under the right scope, it means that elements outside `ng-app` or elements that are detached from the DOM won't be animated. That's exactly how angular-animate works, it takes a specific node as a parameter and searches for ng-app and a body tag in one of his parent elements, and compares it with elements it stashed during initialization. The problem is that the body element he found was not the same as the body element in stash. The reason for this is because you used ng-include on the body tag, so it got replaced, therefore non of the animations should work, since it's outside the application's scope. Next time make sure you don't override tags that angular depends on.

The following template should work instead :

```html
<body ng-app='app'>
  <div ng-controller="ExampleController">
  <select ng-model="selection" ng-options="item for item in items">
  </select>
  <code>selection={{selection}}</code>
  <hr/>
    <div class="animate-switch-container"
      ng-switch on="selection">
        <div class="animate-switch" ng-switch-when="settings">Settings Div</div>
        <div class="animate-switch" ng-switch-when="home">Home Span</div>
        <div class="animate-switch" ng-switch-default>default</div>
    </div>
  </div>
</body>
```

So you see, you can say it's actualy a problem with angular-animate or a problem with your example, not angular-meteor. @Urigo I think this issue can be closed.

**Comment by zakmandhro** [comment]
@DAB0mB Thank you for investigating and the explanation. Makes sense!

I verified this behavior outside of Angular-Meteor (http://embed.plnkr.co/Yq5dvSp7Je5ldktgHZtc) and confirmed this is not a blocker.
