### ISSUE TITLE
Adding More Items To meteor.Collection using infinite scroll.

### ISSUE THREAD

**Issue by nspangler** [Urigo/angular-meteor#681]
I have an collection defined as:

    $scope.someItems = $scope.$meteorCollection( function () {
         return Items.find({}, {limit :  $scope.getReactively('limit')});
     });

   where

    $scope.limit = 10;

   In my html I have:

       <ion-infinite-scroll
                ng-if = "canLoadMore()"
                on-infinite="loadMore()"
                distance="1%">
        </ion-infinite-scroll>

So that when the user gets to the end of the list `loadMore()` is called.

     $scope.loadMore = function () {
        $scope.limit = $scope.limit + 10;
        $timeout( function () {
            $scope.$broadcast('scroll.infiniteScrollComplete');
        }, 1000)
    };

This works great. Unfortunately every time the $scope.limit changes the entire html `<list>` is redrawn as opposed to just adding the next 10 items of the collection to the list. Is this the expected behavior? It doesn't make sense to me for the entire list to be redrawn when the limit of the query is increased.

**Comment by Lavan** [comment]
I assume that you have an ion-list with an ng-repeat attribute somewhere before the ion-infinite-scroll tag. In that case you I think it's enough if you add a "track by item._id" so that angular can map all the new items to the old ones.

**Comment by nspangler** [comment]
@Lavan thanks for the comment! I do have an ion-list with an ng-repeat before the ion-infinite-scroll tag. Could you expound on what what you mean by "track by item._id"? I'm quite sure what the implement would like.

**Comment by jacobdr** [comment]
Can you provide a MeteorPad or github repo to reproduce? 

Not sure this is an angular-meteor issue, but rather the [expected behavior of ng-repeat](https://docs.angularjs.org/api/ng/directive/ngRepeat) when the indexes of a collection change.

Also please check out the changes that I suggested on [this PR](https://github.com/jacobdr/simple-todos-angular/commit/b9c8e402644d926ce25db2b0526857122b2c2404#diff-1fd93fa7f0f2ab3f183a42d7ddf3514cR21) by using orderBy and limitTo filters provided by Angular and see if that resolves this issue.

**Comment by nspangler** [comment]
@jacobdr thanks works perfect! I completely took out the `limit:` in my `js` and instead used the angular `limitTo: limit track by item._id` in the `ng-repeat`.
