### ISSUE TITLE
Undefined check function

### ISSUE THREAD

**Issue by muliyul** [Urigo/angular-meteor#699]
I'm getting this error when splicing a collection array on client side:

ReferenceError: check is not defined
    at Array.angularMeteorCollection.factory.AngularMeteorCollection.remove (angular.js:662)
    at Array.angularMeteorCollection.factory.AngularMeteorCollection._saveChanges (angular.js:836)...

the call to check():
check(keys, [Match.OneOf(String, Mongo.ObjectID)]);

What's up? :D

**Comment by jacobdr** [comment]
Can you please provide a MeteorPad or link to a repo in order to reproduce?

**Comment by muliyul** [comment]
What's a MeteorPad? and I don't have a repo set up because I'm testing capabilities for maybe future projects.

**Comment by jacobdr** [comment]
[MeteorPad](http://meteorpad.com/pad/c5DEtSksntAB7Zmku/Leaderboard) is like jsFiddle for Meteor -- allows you to write Meteor code and share it with others. 

Generally its not a good practice to create a ticket for an issue without providing the code context and information about the environment in which the unexpected behavior occurred. Otherwise how can someone from the project re-produce the error and make sure that they have fixed it?

In your case, did you download the check package? `meteor install check` This may only apply to Meteor v.1.2+

**Comment by ericmcgregor** [comment]
@jacobdr 'meteor add check' worked for me.  I didn't realize that was something i needed to have installed.  Might be a good idea to add that package as a dependency?  Thank you!

**Comment by muliyul** [comment]
That 'meteor add check' and 'meteor add ejson' did the trick. thank you.

**Comment by jacobdr** [comment]
I don't see what that has to do with Angular-Meteor -- its a stand-alone Meteor standard package, just like Accounts (hesitant to use the word base since that's not really true anymore as of version 1.2). 

Did you see `check()` used somewhere in one of the tutorials? If that is the case, then maybe it should be mentioned as a pre-requisite step.

**Comment by muliyul** [comment]
No I didn't see check(). I did however see it was used when I spliced the collection.

**Comment by ericmcgregor** [comment]
Yes, i was using the angular-meteor-generator to test a few things out and it threw an error when trying to remove an item.  it calls check() as part of the AngularMeteorCollection.  Also, good catch @mullyul, it also threw an exception looking for ejson as well.  adding both of those in worked.

**Comment by jacobdr** [comment]
What version of Meteor are you running?

**Comment by jacobdr** [comment]
[Line 123 in angular-meteor-collection.js](https://github.com/Urigo/angular-meteor/blob/master/modules/angular-meteor-collection.js#L123)

Also not sure if it got updated as a [dependency in the latest rc](https://github.com/Urigo/angular-meteor/blob/48586cd13c0594b4ee5f6de21c53f5c7b2f37293/package.js)

Sorry @muliyul you may have been on to something

**Comment by muliyul** [comment]
Sorry for the late response. I was using the latest version of angular server along with the latest version of meteor

**Comment by Urigo** [comment]
Hi, thanks for the good catch.
Just release a new version with the required `check` dependency: `angular@1.0.0-rc.7`
Please let me know if that helped

**Comment by muliyul** [comment]
did you include ejson too?
can't test this because I already resolved the issue on my end.

**Comment by Urigo** [comment]
`check` depends on `ejson` so there is no need..
