### ISSUE TITLE
how to disallow createUser

### ISSUE THREAD

**Issue by cmddavid** [Urigo/angular-meteor#731]
I'm trying to disallow the creation of new users(using $meteor.createUser), i came up with the following:

Meteor.users.allow({
    insert: function (userId) {
        var user = Meteor.users.findOne(userId);
        if(user.role == 'admin'){
            return true;
        } else {
            return false;
        }
    }
});

So only when you are admin, you can create users. But for some reason this doesnt work.

Any ideas?

**Comment by adriangordon1231** [comment]
That is pretty odd. This looks to me like it should work. I am interested to find out why not ... for future reference

**Comment by jacobdr** [comment]
Can you please throw in some debug statements so that we can help track down the issue? 

Not sure if your issue stems from the userId being malformatted, or the Meteor.users call returning an object that doesn't contain the keys that you are looking for. 

Finally, have you removed `insecure` and `autopublish` from your project yet? If need be, you can run the `meteor list` command in order to find out.

```
Meteor.users.allow({
    insert: function (userId) {
        // Make sure this is a well formatted Id like is expected by find one. 
        console.log(userId)
        var user = Meteor.users.findOne(userId);
        // Is the user blank here? Or does it just not contain the user.role field like you are expecting?
        console.log(user.role);
        if(user.role == 'admin'){
            return true;
        } else {
            return false;
        }
    }
});
```

**Comment by Urigo** [comment]
@cmddavid closing until you can provide a runnable reproduction.
thanks
