### ISSUE TITLE
How can i make a reactive Join between two Collections

### ISSUE THREAD

**Issue by dyaa** [Urigo/angular-meteor#749]
I have two Collections `Articles` and `Categories` let's say their documents are like this

**Article**

    {
       "_id": "blabla",
       "title" : "title",
       "description" : "description",
       "categoryId" : "catId"
    }

**Category**

    {
       "_id": "catId",
       "title" : "category",
       "description" : "description"
    }

I want to make a subscription to make them like this

    {
       "_id": "blabla",
       "title" : "title",
       "description" : "description",
       "category" : {
           "title" : "category",
           "description" : "description"
       }
    }

I tried using [publish-composite][1] and here it's my code.
**Server**

    Meteor.publishComposite('articles', {
    	find: function() {
    		return Articles.find({}, { sort: {}, limit: 10 });
    	},
    	children: [
    		{
    			find: function(article) {
    				return Categories.findOne({ _id: article.categoryId });
    			}
    		}
    	]
    });

**And the client angularjs Controller is** 

    angular.module("dee").controller("ArticlesListCtrl", ['$scope', '$meteor', function($scope, $meteor){
    	$scope.articles = $meteor.collection(Articles).subscribe('articles');
    }]);

and the **view** is

    {{ articles | json }}

the problem is it prints the article collection only without the relation.

Here's the [Stackoverflow Question][2] 

  [1]: https://atmospherejs.com/reywood/publish-composite
  [2]: http://stackoverflow.com/questions/33014849/using-publish-composite-with-angular-meteor?stw=2

**Comment by adriangordon1231** [comment]
+1

**Comment by MilosStanic** [comment]
I also tried using publish-composite in the past, without success. So I'm also interested in the answer. 
Meanwhile you have @Deadly0 answered your question on stackoverflow and he referenced his past issue #720

**Comment by Namek** [comment]
@dyaa probably won't solve your problem but I've read that you shouldn't use `findOne()`, but instead `find()` so it gets a cursor. I'm fighting with Angular and `publish-composite` too.

**Comment by Namek** [comment]
OK, I did something! After first debugging it seems like it's reactive.

I assume that Article is supposed to contain many Categories here. So let's make a change so there is no `Article.categoryId` field, instead there's `Category.articleId`.

On the client-side you won't get joined data but you can query for Categories more efficiently because of server-side compositions which we're gonna subscribe to on the client-side.

First, collections (client+server):

```js
Posts = new Mongo.Collection('posts')
Comments = new Mongo.Collection('comments')
```

Then publish composite (server):

```js
Meteor.publishComposite('postsWithComments', {
	find: function() {
		return Posts.find({})
	},
	children: [// comments
		{
			find: function(post) {
				return Comments.find({postId: post._id})
			}
		}
	]
})
```

Then subscribe to published composition in Controller (client):
```js
function DashboardController($meteor) {
	var vm = this;
	vm.posts = $meteor.collection(Posts).subscribe('postsWithComments')
	vm.comments = $meteor.collection(Comments).subscribe('postsWithComments')

	vm.postComments = function(postId) {
		return vm.comments.filter(function(comment) {
			return comment.postId == postId
		})
	}
}
```

And display (of course client):
```html
<div ng-controller="DashboardController as vm">
<div ng-repeat="post in vm.posts">
	<div ng-repeat="comment in vm.postComments(post._id)">
		{{comment.text}}
	</div>
</div>
</div>
```

I'm worried about the `filter` part because it's the client-side. Any further ideas? I'm all ears.

**Comment by adriangordon1231** [comment]
@Namek 

Yess. Thank you. This works

**Comment by Namek** [comment]
maybe @Urigo can help us about the `filter` part? How we do it server-side?

**Comment by netanelgilad** [comment]
@Namek solution is good and it seems there is no better solution. The thing is that publish-composite creates reactive joins by making sure that the collections on the client will contain all the needed documents for a certain parent document, but it does not connect them in any way. Because of that the filter on the client is needed. 
publish composite made sure all the Comments documents that belong to a certain Post are on the client, but that is where its job ends. Now you need to use the filter on the Comments collection to get all of those that relate to a certain Post. If you take a look at the first example in the publish composite repository, you will also see that there they use a template helper to find the Author document that related to a given Post document.
Hope that clears things up a bit. 

You could though use the package collection-helpers to create a function on the Post document that encapsulates the need to find the related comments to make it a bit cleaner.

**Comment by Namek** [comment]
Thanks @netanelgilad I thought it fetches all Comments ever existing and then filters them on the client side for certain parent Post but I made few little tests by looking at meteor's websocket communication and it seems reliable (or I tested it wrong).

**Comment by jerradpatch** [comment]
is publish composite, O(n^3) ? n-collection, n-depth, each node with n-siblings.

**Comment by vfonic** [comment]
@jerradpatch yes it is O(n^3), unfortunately. Let me know if you figure out the solution/alternative.
