### ISSUE TITLE
Blank client screen after step 3.4

### ISSUE THREAD

**Issue by mh-github** [Urigo/angular-meteor#778]
Ref: http://angular-meteor.com/tutorials/angular1/3-way-data-binding

I have been doing the tutorial at angular-meteor.com.
After step 3.4, I don't see anything in the browser.

I am on Ubuntu & Firefox.

My meteor version is 1.2.0.2

Update
---------
I downloaded meteor-angular-socially-step_03 zip file, unzipped it and ran meteor.
It downloaded meteor-tool@1.1.8 and showed an error in index.html file. I removed ng-strict-di from the first line and then the error went away.
But when I run meteor, I still get a blank page.
Step 2 works for me. In this step, the parties array is created in the client side.

**Comment by kvsm** [comment]
I just came across this too. It looks like the server is not parsing *.ng.js files. If you move the Meteor.isServer block into another file, say server.js, it works as expected.

**Comment by mh-github** [comment]
I did a quick check to see if the error is platform specific. Even on Windows 8+ that I use, I got
the same problem.

As suggested by kvsm, I moved the server side code (if Meteor.isServer) to a new file "server.js" and it works. Thanks for the tip Kevin.

Shouldn't the tutorial be updated?

**Comment by dotansimha** [comment]
Hi @mh-github 

Just checked it and you are right, but let me explain some things first:
- The `.ng.js` extension uses for indicating Meteor that this file contains an AngularJS code and should be annotated (to fix angular di issue with minification) and also load it ONLY in the client side.
- The ng-strict-di forces the client to use this type of DI (the output of the `.ng.js` compiler).
- The code in the `Meteor.isServer` will never run because it is inside a file that loaded only in the client side. 

So the best solution as I see it is to split the `Meteor.isServer` code into a separated file and keep the `ng.js` extension.

I will fix it now and update when I am done!

@Urigo

**Comment by dotansimha** [comment]
Fixed in the socially repo, also added a note and updated tutorial:
https://github.com/Urigo/angular-meteor/pull/782
@Urigo

**Comment by Urigo** [comment]
Done and deployed.
Thanks @dotansimha
