### ISSUE TITLE
Autobind flag doesn't work as expected

### ISSUE THREAD

**Issue by daguangli** [Urigo/angular-meteor#796]
The scenario is simple.
        $scope.categories = $scope.$meteorCollection(Categories, false).subscribe("categories");
        $scope.categories.push({ name: 'abc' });
though the autobind is set to 'false', angular-meteor will still create a new doc in Mongo with push.
I am using the latest release, it behaved the same in previous releases.

**Comment by Urigo** [comment]
@daguangli can you please create a repo with an example of that?

**Comment by jacobdr** [comment]
*@daguangl*i when you say that there is a new document in Mongo, are you
referring to:

   1.  the server's Mongo database
   2.  the browser's Minimongo store (e.g. Categories.find({"name":
   "abc}).count() > 0)
   3. the $scope.categories Collection array?

If the first, looks like a good bug candidate. If the last, I think that
that is the expected behavior given the API
<http://angular-meteor.com/api/meteorCollection>.

However, related question:

What is the expected behavior if...

   1. autobind is false
   2. the user pushes an object to the $scope.collection
   3. the user attempts to use the Colletion.save() method
   4. the server returns that the user doesn't have permission to do that
   (Collection.deny returns true)
   5. the attempted write to the client Minimongo collection is evicted
   6. *Does that eviction pass through to the $scope.collection?*

JR

**Comment by daguangli** [comment]
The new doc was created in the server's Mongo database. The expected behavior is it won't be saved until you call Collection.save(), as the autobind was set to false. In some use cases, Collection.save() won't be called at all as there is no need. 
@Urigo I don'k know how to create a repo the demo that. The problem can be reproduced easily just by running a simple meteor app.

**Comment by DAB0mB** [comment]
@daguangli I can't seem to reproduce this problem. There has been some few changes to angular meteor since you opened this issue, can you please check again?

**Comment by daguangli** [comment]
One thing is worth to mention is I am still using insecure package in my app, that probably makes insert from client possible when you do pushing. 
@DAB0mB I am using the latest 1.0.3 release.

**Comment by Urigo** [comment]
As of [Angular Meteor 1.3](http://info.meteor.com/blog/angular-meteor-1.3) we do not recommend using `autobind`. please read inside for more details on why we decided that and how to migrate to the new `helpers` API

**Comment by jacobdr** [comment]
Thanks for the informative post.

I may be out of the loop since I am not a core contributor, but I do
participate on the issues discussions and StackOverflow questions tagged
with angular-meteor. With that as context, do we have a "developers" email
list or forum of communication (IRC, etc.)?

The news in the blog post is great and I am so happy with the progress of
the project and its awesome stewardship. But it would be helpful to someone
like me to hear about major planned changes to the API and/or breaking
changes will in advance of an "official" release and disclosure to the
larger Meteor-blog community.

Happy 1.3 everyone.

**Comment by Urigo** [comment]
I agree.
The point of that version was to make it unnecessary as possible to have a separate place for Angular Meteor developers to talk about things. now they can talk about it with [the rest of the Meteor community](https://forums.meteor.com/) and we will all be aligned.
About the release - my first plan was to do it as a forum post for a release candidate, but then I thought that there are still no breaking changes and everything works as before, so why not....
