### ISSUE TITLE
How to reset party (from Angular-meteor tutorial)

### ISSUE THREAD

**Issue by longxuanho** [Urigo/angular-meteor#949]
From the tutorial, in version 1.2, I can use: 
```javascript
$scope.reset = function() {
    $scope.partyNotAuto.reset();
};
```
But in version 1.3, with new helpers, how can I imply this method? Thanks.

**Comment by dotansimha** [comment]
Hi @longxuanho,
Since we do not use Auto-bind in Angular-Meteor 1.3, there is no need to perform `reset` anymore. 
The object you get on your context (`this` or `$scope`) is just a clone of the real object, and in case of update from the server it will override the object you have now. 
If you still want to modify the object and have the ability to reset it, you can clone it (using `angular.copy` or `_.clone`) and when you want to reset it, just assign it again to the original value.
