### ISSUE TITLE
Getting error Failed to execute 'insertBefore' on 'Node' when trying to use Ionic directives inside of a Blaze template (example repo included)

### ISSUE THREAD

**Issue by lance-anderson** [Urigo/angular-meteor#978]
Forgive me if this is the wrong place to post this; I'm not sure where it should go. The issue seems to be at the intersection of Blaze+Angular+Ionic.

Building upon the [blaze-template](https://github.com/Urigo/angular-meteor/tree/master/examples/1.2/blaze-template) example from this repo, I created an [example repo](https://github.com/lance-anderson/blaze-template-using-ionic) that illustrates what I'm trying to do and what isn't working. Here's a [diff of changes](https://github.com/lance-anderson/blaze-template-using-ionic/compare/58b3761839369cbd8e209b372e2c25b2948dc0a7...68caa481788d9d66b6398bb2acb0f30c6614c72a) between the original example and the few, small changes I made. I also deployed a quick [demo](http://blaze-template-using-ionic.meteor.com) of the issue.

I have a project that is attempting to use Ionic directives inside of a Blaze template. e.g. I'd like to use `<ion-list>` and `<ion-item>` inside of a Blaze template. When attempting to do so, everything works great when the app first renders. However, as seen in the [example](http://blaze-template-using-ionic.meteor.com), when the user attempts to add more "parties" it throws the following javascript error:
```
Error: Failed to execute 'insertBefore' on 'Node': The node before which the new node is to be inserted is not a child of this node.
    at Error (native)
    at Function.DOMRange._insertNodeWithHooks (http://localhost:3200/packages/blaze.js?695c7798b7f4eebed3f8ce0cbb17c21748ff8ba8:385:12)
    at Function.DOMRange._insert (http://localhost:3200/packages/blaze.js?695c7798b7f4eebed3f8ce0cbb17c21748ff8ba8:354:16)
    at DOMRange.attach (http://localhost:3200/packages/blaze.js?695c7798b7f4eebed3f8ce0cbb17c21748ff8ba8:431:16)
    at Function.DOMRange._insert (http://localhost:3200/packages/blaze.js?695c7798b7f4eebed3f8ce0cbb17c21748ff8ba8:349:7)
    at DOMRange.addMember (http://localhost:3200/packages/blaze.js?695c7798b7f4eebed3f8ce0cbb17c21748ff8ba8:553:14)
    at http://localhost:3200/packages/blaze.js?695c7798b7f4eebed3f8ce0cbb17c21748ff8ba8:2800:32
    at Object.Tracker.nonreactive (http://localhost:3200/packages/tracker.js?7776276660c988c38fed448d8262b925dffb5bc3:615:12)
    at Object.eachView.stopHandle.ObserveSequence.observe.addedAt (http://localhost:3200/packages/blaze.js?695c7798b7f4eebed3f8ce0cbb17c21748ff8ba8:2772:17)
    at Object.diffFn.addedBefore (http://localhost:3200/packages/observe-sequence.js?e0b5ec6321580efa20bf31f5a1ae4c52f05f38b5:231:17)
```

**Steps to reproduce**
1. Go to http://blaze-template-using-ionic.meteor.com
2. Add a new Party name &amp; description
3. In the browser observe that the new Party is added to the list above but not the list below
4. In the console observe that the `Failed to execute 'insertBefore' on 'Node'` error

**What's different between the two approaches**
In this example, the primary difference is that the top section, which works, is using `<div class="item">` while the bottom section, which does not work, uses `<ion-list can-swipe="true" show-delete="false">`.

I'm at a loss as to what the issue is let alone how to resolve it. Any input would be _greatly_ appreciated as I would _really_ like to be able to keep using Blaze and Ionic directives together. But at the moment, this seems to be a show-stopper.

**Comment by Urigo** [comment]
I haven;t looked at it deeply yet, but can you check if it's working better when using version 1.2.1 of angular-with-blaze?

**Comment by lance-anderson** [comment]
Thanks for getting back to me; I appreciate it. I've tried `angular-with-blaze@1.2.0`, `angular-with-blaze@1.2.1`, and `angular-with-blaze@1.3.1` all with the same result.

**Comment by lance-anderson** [comment]
Hi @Urigo. Any chance of this being on your radar in the near future?

**Comment by DAB0mB** [comment]
@lance-anderson There is a certain conflict between `ionic` and `blaze`, the following flow describes it:

- `ionic` adds the element `div.list` to every `ion-list` being defined.
- `blaze` iterates the list using `#each` helper, and uses the parent node to insert a new item.

You would expect `ion-list` to be the parent node, but no, the parent node is actually `div.list`, because of how `ionic` works. So `blaze` is actually being fooled and tries to add the items to the wrong element, which causes an error.

You can sort of fix it using the following template:

```html
<template name="partiesBlazeTemplateUsingIonicDirectives">
  <h4>Angular parties inside Blaze using Ionic Directives:</h4>
  <ion-list can-swipe="true" show-delete="false">
    <div class="list">
      {{#each parties}}
        {{> partyIonicDirectives}}
      {{/each}}
    </div>
  </ion-list>
</template>
```

The problem is, that the options you specify to `ion-list` won't be applied, so the `delete` button would be visible, which I haven't figured out of how to solve yet.

I will update this post once I make progress, but just to make it clear, I don't think this problem is related to `angular-meteor`, it's either `blaze` or `ionic`. And if you find a solution, do tell.

cheers!

**Comment by lance-anderson** [comment]
Thanks for sharing the info. I agree with your observations. Unfortunately, I have not found a solution and I'm exploring alternative approaches to using Ionic and Blaze together.

**Comment by mervynteo** [comment]
Im having this problem too using meteoric which has no angular at all, so I can confirm that issue is as what @DAB0mB has mentioned. However adding <div> works for some but not all. It only happened when I upgraded my meteor to 1.2+. Let me know of the solution if any ...perhaps would post it to meteor devs too.

**Comment by Urigo** [comment]
please re-open this issue on Ionic or Blaze
