### ISSUE TITLE
(v1.3.1) Two warnings unrelated to app code

### ISSUE THREAD

**Issue by MilosStanic** [Urigo/angular-meteor#984]
Hi all, 

I've made a total move to v.1.3.1 in my app, and everything works perfectly, as far as I can see. 
The new `this.getReactively` syntax works fantastic, and is a perfect fit for both using `$scope` and using `controllerAs` syntax. 

However, I'm getting two warnings about deprecated methods, even though I eliminated all old stuff from my code: 

```
collection-extensions.js:25 `Meteor.addCollectionExtension` is deprecated, please use `CollectionExtensions.addExtension`
angular-meteor-user.js:85 [angular-meteor.$rootScope.currentUser/loggingIn] Please note that this functionality has migrated to a separate package and will be deprecated in 1.4.0.  For more info: http://www.angular-meteor.com/api/1.3.0/auth
```
I'm totally positive I don't use `Meteor.addCollectionExtension` anywhere in my code. 
And I triple checked to remove all references to `$root.currentUser`, `$root.loggingIn`, `$rootScope.currentUser`, and `$rootScope.loggingIn`.

**Comment by Urigo** [comment]
mmmm about collection extensions, I have no idea, we don't use it anywhere (https://github.com/rclai/meteor-collection-extensions)

About the `currentUser/loggingIn` warning, I think I will remove it because if I'll place it somewhere else, it will pop up every time the user will change and that is too much

**Comment by MilosStanic** [comment]
I recieved a warning about some dep package needed to be updated manually when I was moving to v1.3.1, so maybe this package uses collection extensions. Unfortunately I didn't write it down. 
And this seems like a Meteor core warning.

**Comment by ronaldso55** [comment]
I have a Meteor Angular app based on v1.3.4 and I see the same issue, except that the second warning comes from angular-meteor-data.js instead of angular-meteor-user.js.  How do we fix that?

```
Meteor.addCollectionExtension` is deprecated, please use `CollectionExtensions.addExtension`
lai_collection-extensions.js (line 56)

[angular-meteor.$rootScope.currentUser/loggingIn] Please note that this functionality has migrated to a separate package and will be deprecated in 1.4.0.  For more info: http://www.angular-meteor.com/api/1.3.2/auth (angular-meteor-data.js line 1229)
```

**Comment by wohlford** [comment]
I'm getting this message too. Not sure why, but it occurred after I ran 'meteor update' recently. Trying to track this down.

**Comment by wohlford** [comment]
Turns out my issue is related to the use of msavin:mongol the "In-App MongoDB Editor." Once I removed that package the warning disappeared. It has a dependency on dburles:mongo-collection-instances which I believe is where the error is being generated. I've readded the msavin:mongol with its dependencies to my meteor project and now the message has gone away. Had planned to submit a bug report, but can't reproduce anymore. :-/
